// Code generated by Sideko (sideko.dev)

package client

import (
	sdkcore "apigee_api/core"
	http "net/http"
)

// Provide your own http.Client to be used for all requests
func WithHTTPClient(httpClient *http.Client) func(*sdkcore.CoreClient) {
	return func(c *sdkcore.CoreClient) {
		c.HttpClient = httpClient
	}
}

// Provide non-default baseURL for all requests
func WithBaseURL(baseURL string) func(*sdkcore.CoreClient) {
	return func(c *sdkcore.CoreClient) {
		c.BaseURL = baseURL
	}
}

type RequestModifier = func(req *http.Request) error

// Provide modifiers to be applied to all client requests
func WithModifiers(modifiers ...RequestModifier) func(*sdkcore.CoreClient) {
	return func(c *sdkcore.CoreClient) {
		c.Modifiers = append(c.Modifiers, modifiers...)
	}
}

// register auth builders (keep comment for code generation)

func WithOauth2(val string) func(*sdkcore.CoreClient) {
	return func(c *sdkcore.CoreClient) {
		c.Auth["Oauth2"] = func(request *http.Request) {
			request.Header.Add("Authorization", "Bearer "+val)
		}
	}
}

func WithOauth2c(val string) func(*sdkcore.CoreClient) {
	return func(c *sdkcore.CoreClient) {
		c.Auth["Oauth2c"] = func(request *http.Request) {
			request.Header.Add("Authorization", "Bearer "+val)
		}
	}
}
