// Code generated by Sideko (sideko.dev)

package client

import (
	sdkcore "apigee_api/core"
	v1 "apigee_api/resources/v1"
)

type Client struct {
	coreClient *sdkcore.CoreClient
	V1         *v1.Client
}

// Instantiate a new API client
func NewClient(builders ...func(*sdkcore.CoreClient)) *Client {
	baseURL := `https://apigee.googleapis.com/`
	coreClient := sdkcore.NewCoreClient(baseURL)
	for _, b := range builders {
		b(coreClient)
	}

	client := Client{
		coreClient: coreClient,
		V1:         v1.NewClient(coreClient),
	}

	return &client
}

// register api methods (keep comment for code generation)
