// Code generated by Sideko (sideko.dev)
package operations

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type ListRequest struct {
	Name           string                                                `json:"name"`
	QueryXgafv     nullable.Nullable[types.GetV1NameOperationsXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                             `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.GetV1NameOperationsAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                             `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                             `json:"fields,omitempty"`
	Filter         nullable.Nullable[string]                             `json:"filter,omitempty"`
	Key            nullable.Nullable[string]                             `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                             `json:"oauthToken,omitempty"`
	PageSize       nullable.Nullable[int]                                `json:"pageSize,omitempty"`
	PageToken      nullable.Nullable[string]                             `json:"pageToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                               `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                             `json:"quotaUser,omitempty"`
	UploadType     nullable.Nullable[string]                             `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                             `json:"uploadProtocol,omitempty"`
}
