// Code generated by Sideko (sideko.dev)
package set_addons

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type CreateRequest struct {
	Org            string                                               `json:"org"`
	QueryXgafv     nullable.Nullable[types.PostV1OrgSetAddonsXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                            `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.PostV1OrgSetAddonsAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                            `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                            `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                            `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                            `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                              `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                            `json:"quotaUser,omitempty"`
	UploadType     nullable.Nullable[string]                            `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                            `json:"uploadProtocol,omitempty"`
	Data           types.GoogleCloudApigeeV1SetAddonsRequest            `json:"data"`
}
