// Code generated by Sideko (sideko.dev)
package aliases

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type CreateRequest struct {
	Parent                  string                                                `json:"parent"`
	QueryXgafv              nullable.Nullable[types.PostV1ParentAliasesXgafvEnum] `json:"queryXgafv,omitempty"`
	QueryPassword           nullable.Nullable[string]                             `json:"queryPassword,omitempty"`
	AccessToken             nullable.Nullable[string]                             `json:"accessToken,omitempty"`
	Alias                   nullable.Nullable[string]                             `json:"alias,omitempty"`
	Alt                     nullable.Nullable[types.PostV1ParentAliasesAltEnum]   `json:"alt,omitempty"`
	Callback                nullable.Nullable[string]                             `json:"callback,omitempty"`
	Fields                  nullable.Nullable[string]                             `json:"fields,omitempty"`
	Format                  nullable.Nullable[string]                             `json:"format,omitempty"`
	IgnoreExpiryValidation  nullable.Nullable[bool]                               `json:"ignoreExpiryValidation,omitempty"`
	IgnoreNewlineValidation nullable.Nullable[bool]                               `json:"ignoreNewlineValidation,omitempty"`
	Key                     nullable.Nullable[string]                             `json:"key,omitempty"`
	OauthToken              nullable.Nullable[string]                             `json:"oauthToken,omitempty"`
	PrettyPrint             nullable.Nullable[bool]                               `json:"prettyPrint,omitempty"`
	QuotaUser               nullable.Nullable[string]                             `json:"quotaUser,omitempty"`
	UploadType              nullable.Nullable[string]                             `json:"uploadType,omitempty"`
	UploadProtocol          nullable.Nullable[string]                             `json:"uploadProtocol,omitempty"`
	Data                    types.GoogleApiHttpBody                               `json:"data"`
}
