// Code generated by Sideko (sideko.dev)
package types

type DeleteV1ParentResourcefilesTypeNameAltEnum string

const (
	DeleteV1ParentResourcefilesTypeNameAltEnumJson  DeleteV1ParentResourcefilesTypeNameAltEnum = "json"
	DeleteV1ParentResourcefilesTypeNameAltEnumMedia DeleteV1ParentResourcefilesTypeNameAltEnum = "media"
	DeleteV1ParentResourcefilesTypeNameAltEnumProto DeleteV1ParentResourcefilesTypeNameAltEnum = "proto"
)
