// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameDeploymentsAltEnum string

const (
	DeleteV1NameDeploymentsAltEnumJson  DeleteV1NameDeploymentsAltEnum = "json"
	DeleteV1NameDeploymentsAltEnumMedia DeleteV1NameDeploymentsAltEnum = "media"
	DeleteV1NameDeploymentsAltEnumProto DeleteV1NameDeploymentsAltEnum = "proto"
)
