// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameDataAltEnum string

const (
	DeleteV1NameDataAltEnumJson  DeleteV1NameDataAltEnum = "json"
	DeleteV1NameDataAltEnumMedia DeleteV1NameDataAltEnum = "media"
	DeleteV1NameDataAltEnumProto DeleteV1NameDataAltEnum = "proto"
)
