// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameXgafvEnum string

const (
	DeleteV1NameXgafvEnum1 DeleteV1NameXgafvEnum = "1"
	DeleteV1NameXgafvEnum2 DeleteV1NameXgafvEnum = "2"
)
