// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameAltEnum string

const (
	DeleteV1NameAltEnumJson  DeleteV1NameAltEnum = "json"
	DeleteV1NameAltEnumMedia DeleteV1NameAltEnum = "media"
	DeleteV1NameAltEnumProto DeleteV1NameAltEnum = "proto"
)
