// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameDataXgafvEnum string

const (
	DeleteV1NameDataXgafvEnum1 DeleteV1NameDataXgafvEnum = "1"
	DeleteV1NameDataXgafvEnum2 DeleteV1NameDataXgafvEnum = "2"
)
