// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameDeploymentsXgafvEnum string

const (
	DeleteV1NameDeploymentsXgafvEnum1 DeleteV1NameDeploymentsXgafvEnum = "1"
	DeleteV1NameDeploymentsXgafvEnum2 DeleteV1NameDeploymentsXgafvEnum = "2"
)
