// Code generated by Sideko (sideko.dev)
package types

type DeleteV1NameRetentionEnum string

const (
	DeleteV1NameRetentionEnumDeletionRetentionUnspecified DeleteV1NameRetentionEnum = "DELETION_RETENTION_UNSPECIFIED"
	DeleteV1NameRetentionEnumMinimum                      DeleteV1NameRetentionEnum = "MINIMUM"
)
