// Code generated by Sideko (sideko.dev)
package types

type GetV1NameOperationsAltEnum string

const (
	GetV1NameOperationsAltEnumJson  GetV1NameOperationsAltEnum = "json"
	GetV1NameOperationsAltEnumMedia GetV1NameOperationsAltEnum = "media"
	GetV1NameOperationsAltEnumProto GetV1NameOperationsAltEnum = "proto"
)
