// Code generated by Sideko (sideko.dev)
package types

type GetV1ResourceGetIamPolicyAltEnum string

const (
	GetV1ResourceGetIamPolicyAltEnumJson  GetV1ResourceGetIamPolicyAltEnum = "json"
	GetV1ResourceGetIamPolicyAltEnumMedia GetV1ResourceGetIamPolicyAltEnum = "media"
	GetV1ResourceGetIamPolicyAltEnumProto GetV1ResourceGetIamPolicyAltEnum = "proto"
)
