// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAttachmentsAltEnum string

const (
	GetV1ParentAttachmentsAltEnumJson  GetV1ParentAttachmentsAltEnum = "json"
	GetV1ParentAttachmentsAltEnumMedia GetV1ParentAttachmentsAltEnum = "media"
	GetV1ParentAttachmentsAltEnumProto GetV1ParentAttachmentsAltEnum = "proto"
)
