// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAppsAltEnum string

const (
	GetV1ParentAppsAltEnumJson  GetV1ParentAppsAltEnum = "json"
	GetV1ParentAppsAltEnumMedia GetV1ParentAppsAltEnum = "media"
	GetV1ParentAppsAltEnumProto GetV1ParentAppsAltEnum = "proto"
)
