// Code generated by Sideko (sideko.dev)
package types

type GetV1NameListRevisionsAltEnum string

const (
	GetV1NameListRevisionsAltEnumJson  GetV1NameListRevisionsAltEnum = "json"
	GetV1NameListRevisionsAltEnumMedia GetV1NameListRevisionsAltEnum = "media"
	GetV1NameListRevisionsAltEnumProto GetV1NameListRevisionsAltEnum = "proto"
)
