// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentQueriesAltEnum string

const (
	GetV1ParentQueriesAltEnumJson  GetV1ParentQueriesAltEnum = "json"
	GetV1ParentQueriesAltEnumMedia GetV1ParentQueriesAltEnum = "media"
	GetV1ParentQueriesAltEnumProto GetV1ParentQueriesAltEnum = "proto"
)
