// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApiproductsAltEnum string

const (
	GetV1ParentApiproductsAltEnumJson  GetV1ParentApiproductsAltEnum = "json"
	GetV1ParentApiproductsAltEnumMedia GetV1ParentApiproductsAltEnum = "media"
	GetV1ParentApiproductsAltEnumProto GetV1ParentApiproductsAltEnum = "proto"
)
