// Code generated by Sideko (sideko.dev)
package types

type GetV1NameOperationsXgafvEnum string

const (
	GetV1NameOperationsXgafvEnum1 GetV1NameOperationsXgafvEnum = "1"
	GetV1NameOperationsXgafvEnum2 GetV1NameOperationsXgafvEnum = "2"
)
