// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDebugsessionsXgafvEnum string

const (
	GetV1ParentDebugsessionsXgafvEnum1 GetV1ParentDebugsessionsXgafvEnum = "1"
	GetV1ParentDebugsessionsXgafvEnum2 GetV1ParentDebugsessionsXgafvEnum = "2"
)
