// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDatacollectorsXgafvEnum string

const (
	GetV1ParentDatacollectorsXgafvEnum1 GetV1ParentDatacollectorsXgafvEnum = "1"
	GetV1ParentDatacollectorsXgafvEnum2 GetV1ParentDatacollectorsXgafvEnum = "2"
)
