// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentXgafvEnum string

const (
	GetV1ParentXgafvEnum1 GetV1ParentXgafvEnum = "1"
	GetV1ParentXgafvEnum2 GetV1ParentXgafvEnum = "2"
)
