// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAnalyticsExportsXgafvEnum string

const (
	GetV1ParentAnalyticsExportsXgafvEnum1 GetV1ParentAnalyticsExportsXgafvEnum = "1"
	GetV1ParentAnalyticsExportsXgafvEnum2 GetV1ParentAnalyticsExportsXgafvEnum = "2"
)
