// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentArchiveDeploymentsAltEnum string

const (
	GetV1ParentArchiveDeploymentsAltEnumJson  GetV1ParentArchiveDeploymentsAltEnum = "json"
	GetV1ParentArchiveDeploymentsAltEnumMedia GetV1ParentArchiveDeploymentsAltEnum = "media"
	GetV1ParentArchiveDeploymentsAltEnumProto GetV1ParentArchiveDeploymentsAltEnum = "proto"
)
