// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesTypeAltEnum string

const (
	GetV1ParentResourcefilesTypeAltEnumJson  GetV1ParentResourcefilesTypeAltEnum = "json"
	GetV1ParentResourcefilesTypeAltEnumMedia GetV1ParentResourcefilesTypeAltEnum = "media"
	GetV1ParentResourcefilesTypeAltEnumProto GetV1ParentResourcefilesTypeAltEnum = "proto"
)
