// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDevelopersXgafvEnum string

const (
	GetV1ParentDevelopersXgafvEnum1 GetV1ParentDevelopersXgafvEnum = "1"
	GetV1ParentDevelopersXgafvEnum2 GetV1ParentDevelopersXgafvEnum = "2"
)
