// Code generated by Sideko (sideko.dev)
package types

type GetV1NameCsrXgafvEnum string

const (
	GetV1NameCsrXgafvEnum1 GetV1NameCsrXgafvEnum = "1"
	GetV1NameCsrXgafvEnum2 GetV1NameCsrXgafvEnum = "2"
)
