// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentEnvgroupsAltEnum string

const (
	GetV1ParentEnvgroupsAltEnumJson  GetV1ParentEnvgroupsAltEnum = "json"
	GetV1ParentEnvgroupsAltEnumMedia GetV1ParentEnvgroupsAltEnum = "media"
	GetV1ParentEnvgroupsAltEnumProto GetV1ParentEnvgroupsAltEnum = "proto"
)
