// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesAltEnum string

const (
	GetV1ParentResourcefilesAltEnumJson  GetV1ParentResourcefilesAltEnum = "json"
	GetV1ParentResourcefilesAltEnumMedia GetV1ParentResourcefilesAltEnum = "media"
	GetV1ParentResourcefilesAltEnumProto GetV1ParentResourcefilesAltEnum = "proto"
)
