// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDeploymentsXgafvEnum string

const (
	GetV1ParentDeploymentsXgafvEnum1 GetV1ParentDeploymentsXgafvEnum = "1"
	GetV1ParentDeploymentsXgafvEnum2 GetV1ParentDeploymentsXgafvEnum = "2"
)
