// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApisXgafvEnum string

const (
	GetV1ParentApisXgafvEnum1 GetV1ParentApisXgafvEnum = "1"
	GetV1ParentApisXgafvEnum2 GetV1ParentApisXgafvEnum = "2"
)
