// Code generated by Sideko (sideko.dev)
package types

type GetV1NameFormatEnum string

const (
	GetV1NameFormatEnumBasic                        GetV1NameFormatEnum = "BASIC"
	GetV1NameFormatEnumFull                         GetV1NameFormatEnum = "FULL"
	GetV1NameFormatEnumIngressConfigViewUnspecified GetV1NameFormatEnum = "INGRESS_CONFIG_VIEW_UNSPECIFIED"
)
