// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentReportsAltEnum string

const (
	GetV1ParentReportsAltEnumJson  GetV1ParentReportsAltEnum = "json"
	GetV1ParentReportsAltEnumMedia GetV1ParentReportsAltEnum = "media"
	GetV1ParentReportsAltEnumProto GetV1ParentReportsAltEnum = "proto"
)
