// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentEntriesAltEnum string

const (
	GetV1ParentEntriesAltEnumJson  GetV1ParentEntriesAltEnum = "json"
	GetV1ParentEntriesAltEnumMedia GetV1ParentEntriesAltEnum = "media"
	GetV1ParentEntriesAltEnumProto GetV1ParentEntriesAltEnum = "proto"
)
