// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentInstancesAltEnum string

const (
	GetV1ParentInstancesAltEnumJson  GetV1ParentInstancesAltEnum = "json"
	GetV1ParentInstancesAltEnumMedia GetV1ParentInstancesAltEnum = "media"
	GetV1ParentInstancesAltEnumProto GetV1ParentInstancesAltEnum = "proto"
)
