// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApiproductsXgafvEnum string

const (
	GetV1ParentApiproductsXgafvEnum1 GetV1ParentApiproductsXgafvEnum = "1"
	GetV1ParentApiproductsXgafvEnum2 GetV1ParentApiproductsXgafvEnum = "2"
)
