// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesXgafvEnum string

const (
	GetV1ParentResourcefilesXgafvEnum1 GetV1ParentResourcefilesXgafvEnum = "1"
	GetV1ParentResourcefilesXgafvEnum2 GetV1ParentResourcefilesXgafvEnum = "2"
)
