// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentEndpointAttachmentsXgafvEnum string

const (
	GetV1ParentEndpointAttachmentsXgafvEnum1 GetV1ParentEndpointAttachmentsXgafvEnum = "1"
	GetV1ParentEndpointAttachmentsXgafvEnum2 GetV1ParentEndpointAttachmentsXgafvEnum = "2"
)
