// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSharedflowsAltEnum string

const (
	GetV1ParentSharedflowsAltEnumJson  GetV1ParentSharedflowsAltEnum = "json"
	GetV1ParentSharedflowsAltEnumMedia GetV1ParentSharedflowsAltEnum = "media"
	GetV1ParentSharedflowsAltEnumProto GetV1ParentSharedflowsAltEnum = "proto"
)
