// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesTypeXgafvEnum string

const (
	GetV1ParentResourcefilesTypeXgafvEnum1 GetV1ParentResourcefilesTypeXgafvEnum = "1"
	GetV1ParentResourcefilesTypeXgafvEnum2 GetV1ParentResourcefilesTypeXgafvEnum = "2"
)
