// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentRateplansXgafvEnum string

const (
	GetV1ParentRateplansXgafvEnum1 GetV1ParentRateplansXgafvEnum = "1"
	GetV1ParentRateplansXgafvEnum2 GetV1ParentRateplansXgafvEnum = "2"
)
