// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentRateplansStateEnum string

const (
	GetV1ParentRateplansStateEnumDraft            GetV1ParentRateplansStateEnum = "DRAFT"
	GetV1ParentRateplansStateEnumPublished        GetV1ParentRateplansStateEnum = "PUBLISHED"
	GetV1ParentRateplansStateEnumStateUnspecified GetV1ParentRateplansStateEnum = "STATE_UNSPECIFIED"
)
