// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentEnvgroupsXgafvEnum string

const (
	GetV1ParentEnvgroupsXgafvEnum1 GetV1ParentEnvgroupsXgafvEnum = "1"
	GetV1ParentEnvgroupsXgafvEnum2 GetV1ParentEnvgroupsXgafvEnum = "2"
)
