// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAttributesXgafvEnum string

const (
	GetV1ParentAttributesXgafvEnum1 GetV1ParentAttributesXgafvEnum = "1"
	GetV1ParentAttributesXgafvEnum2 GetV1ParentAttributesXgafvEnum = "2"
)
