// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityProfilesAltEnum string

const (
	GetV1ParentSecurityProfilesAltEnumJson  GetV1ParentSecurityProfilesAltEnum = "json"
	GetV1ParentSecurityProfilesAltEnumMedia GetV1ParentSecurityProfilesAltEnum = "media"
	GetV1ParentSecurityProfilesAltEnumProto GetV1ParentSecurityProfilesAltEnum = "proto"
)
