// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDatacollectorsAltEnum string

const (
	GetV1ParentDatacollectorsAltEnumJson  GetV1ParentDatacollectorsAltEnum = "json"
	GetV1ParentDatacollectorsAltEnumMedia GetV1ParentDatacollectorsAltEnum = "media"
	GetV1ParentDatacollectorsAltEnumProto GetV1ParentDatacollectorsAltEnum = "proto"
)
