// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentHostSecurityReportsAltEnum string

const (
	GetV1ParentHostSecurityReportsAltEnumJson  GetV1ParentHostSecurityReportsAltEnum = "json"
	GetV1ParentHostSecurityReportsAltEnumMedia GetV1ParentHostSecurityReportsAltEnum = "media"
	GetV1ParentHostSecurityReportsAltEnumProto GetV1ParentHostSecurityReportsAltEnum = "proto"
)
