// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDevelopersAltEnum string

const (
	GetV1ParentDevelopersAltEnumJson  GetV1ParentDevelopersAltEnum = "json"
	GetV1ParentDevelopersAltEnumMedia GetV1ParentDevelopersAltEnum = "media"
	GetV1ParentDevelopersAltEnumProto GetV1ParentDevelopersAltEnum = "proto"
)
