// Code generated by Sideko (sideko.dev)
package types

type GetV1NameDeploymentsXgafvEnum string

const (
	GetV1NameDeploymentsXgafvEnum1 GetV1NameDeploymentsXgafvEnum = "1"
	GetV1NameDeploymentsXgafvEnum2 GetV1NameDeploymentsXgafvEnum = "2"
)
