// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentHostQueriesAltEnum string

const (
	GetV1ParentHostQueriesAltEnumJson  GetV1ParentHostQueriesAltEnum = "json"
	GetV1ParentHostQueriesAltEnumMedia GetV1ParentHostQueriesAltEnum = "media"
	GetV1ParentHostQueriesAltEnumProto GetV1ParentHostQueriesAltEnum = "proto"
)
