// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentHostQueriesXgafvEnum string

const (
	GetV1ParentHostQueriesXgafvEnum1 GetV1ParentHostQueriesXgafvEnum = "1"
	GetV1ParentHostQueriesXgafvEnum2 GetV1ParentHostQueriesXgafvEnum = "2"
)
