// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApisAltEnum string

const (
	GetV1ParentApisAltEnumJson  GetV1ParentApisAltEnum = "json"
	GetV1ParentApisAltEnumMedia GetV1ParentApisAltEnum = "media"
	GetV1ParentApisAltEnumProto GetV1ParentApisAltEnum = "proto"
)
