// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentHostSecurityReportsXgafvEnum string

const (
	GetV1ParentHostSecurityReportsXgafvEnum1 GetV1ParentHostSecurityReportsXgafvEnum = "1"
	GetV1ParentHostSecurityReportsXgafvEnum2 GetV1ParentHostSecurityReportsXgafvEnum = "2"
)
