// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentOverridesXgafvEnum string

const (
	GetV1ParentOverridesXgafvEnum1 GetV1ParentOverridesXgafvEnum = "1"
	GetV1ParentOverridesXgafvEnum2 GetV1ParentOverridesXgafvEnum = "2"
)
