// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAnalyticsDatastoresAltEnum string

const (
	GetV1ParentAnalyticsDatastoresAltEnumJson  GetV1ParentAnalyticsDatastoresAltEnum = "json"
	GetV1ParentAnalyticsDatastoresAltEnumMedia GetV1ParentAnalyticsDatastoresAltEnum = "media"
	GetV1ParentAnalyticsDatastoresAltEnumProto GetV1ParentAnalyticsDatastoresAltEnum = "proto"
)
