// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSubscriptionsAltEnum string

const (
	GetV1ParentSubscriptionsAltEnumJson  GetV1ParentSubscriptionsAltEnum = "json"
	GetV1ParentSubscriptionsAltEnumMedia GetV1ParentSubscriptionsAltEnum = "media"
	GetV1ParentSubscriptionsAltEnumProto GetV1ParentSubscriptionsAltEnum = "proto"
)
