// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSharedflowsXgafvEnum string

const (
	GetV1ParentSharedflowsXgafvEnum1 GetV1ParentSharedflowsXgafvEnum = "1"
	GetV1ParentSharedflowsXgafvEnum2 GetV1ParentSharedflowsXgafvEnum = "2"
)
