// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApicategoriesXgafvEnum string

const (
	GetV1ParentApicategoriesXgafvEnum1 GetV1ParentApicategoriesXgafvEnum = "1"
	GetV1ParentApicategoriesXgafvEnum2 GetV1ParentApicategoriesXgafvEnum = "2"
)
