// Code generated by Sideko (sideko.dev)
package types

type GetV1NameCertificateAltEnum string

const (
	GetV1NameCertificateAltEnumJson  GetV1NameCertificateAltEnum = "json"
	GetV1NameCertificateAltEnumMedia GetV1NameCertificateAltEnum = "media"
	GetV1NameCertificateAltEnumProto GetV1NameCertificateAltEnum = "proto"
)
