// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentInstancesXgafvEnum string

const (
	GetV1ParentInstancesXgafvEnum1 GetV1ParentInstancesXgafvEnum = "1"
	GetV1ParentInstancesXgafvEnum2 GetV1ParentInstancesXgafvEnum = "2"
)
