// Code generated by Sideko (sideko.dev)
package types

type GetV1NameDeploymentsAltEnum string

const (
	GetV1NameDeploymentsAltEnumJson  GetV1NameDeploymentsAltEnum = "json"
	GetV1NameDeploymentsAltEnumMedia GetV1NameDeploymentsAltEnum = "media"
	GetV1NameDeploymentsAltEnumProto GetV1NameDeploymentsAltEnum = "proto"
)
