// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentReportsXgafvEnum string

const (
	GetV1ParentReportsXgafvEnum1 GetV1ParentReportsXgafvEnum = "1"
	GetV1ParentReportsXgafvEnum2 GetV1ParentReportsXgafvEnum = "2"
)
