// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDeploymentsAltEnum string

const (
	GetV1ParentDeploymentsAltEnumJson  GetV1ParentDeploymentsAltEnum = "json"
	GetV1ParentDeploymentsAltEnumMedia GetV1ParentDeploymentsAltEnum = "media"
	GetV1ParentDeploymentsAltEnumProto GetV1ParentDeploymentsAltEnum = "proto"
)
