// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentRateplansAltEnum string

const (
	GetV1ParentRateplansAltEnumJson  GetV1ParentRateplansAltEnum = "json"
	GetV1ParentRateplansAltEnumMedia GetV1ParentRateplansAltEnum = "media"
	GetV1ParentRateplansAltEnumProto GetV1ParentRateplansAltEnum = "proto"
)
