// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentEntriesXgafvEnum string

const (
	GetV1ParentEntriesXgafvEnum1 GetV1ParentEntriesXgafvEnum = "1"
	GetV1ParentEntriesXgafvEnum2 GetV1ParentEntriesXgafvEnum = "2"
)
