// Code generated by Sideko (sideko.dev)
package types

type GetV1NameCertificateXgafvEnum string

const (
	GetV1NameCertificateXgafvEnum1 GetV1NameCertificateXgafvEnum = "1"
	GetV1NameCertificateXgafvEnum2 GetV1NameCertificateXgafvEnum = "2"
)
