// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentApicategoriesAltEnum string

const (
	GetV1ParentApicategoriesAltEnumJson  GetV1ParentApicategoriesAltEnum = "json"
	GetV1ParentApicategoriesAltEnumMedia GetV1ParentApicategoriesAltEnum = "media"
	GetV1ParentApicategoriesAltEnumProto GetV1ParentApicategoriesAltEnum = "proto"
)
