// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentArchiveDeploymentsXgafvEnum string

const (
	GetV1ParentArchiveDeploymentsXgafvEnum1 GetV1ParentArchiveDeploymentsXgafvEnum = "1"
	GetV1ParentArchiveDeploymentsXgafvEnum2 GetV1ParentArchiveDeploymentsXgafvEnum = "2"
)
