// Code generated by Sideko (sideko.dev)
package types

type GetV1NameGetProjectMappingAltEnum string

const (
	GetV1NameGetProjectMappingAltEnumJson  GetV1NameGetProjectMappingAltEnum = "json"
	GetV1NameGetProjectMappingAltEnumMedia GetV1NameGetProjectMappingAltEnum = "media"
	GetV1NameGetProjectMappingAltEnumProto GetV1NameGetProjectMappingAltEnum = "proto"
)
