// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentQueriesXgafvEnum string

const (
	GetV1ParentQueriesXgafvEnum1 GetV1ParentQueriesXgafvEnum = "1"
	GetV1ParentQueriesXgafvEnum2 GetV1ParentQueriesXgafvEnum = "2"
)
