// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityIncidentsAltEnum string

const (
	GetV1ParentSecurityIncidentsAltEnumJson  GetV1ParentSecurityIncidentsAltEnum = "json"
	GetV1ParentSecurityIncidentsAltEnumMedia GetV1ParentSecurityIncidentsAltEnum = "media"
	GetV1ParentSecurityIncidentsAltEnumProto GetV1ParentSecurityIncidentsAltEnum = "proto"
)
