// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAnalyticsDatastoresXgafvEnum string

const (
	GetV1ParentAnalyticsDatastoresXgafvEnum1 GetV1ParentAnalyticsDatastoresXgafvEnum = "1"
	GetV1ParentAnalyticsDatastoresXgafvEnum2 GetV1ParentAnalyticsDatastoresXgafvEnum = "2"
)
