// Code generated by Sideko (sideko.dev)
package types

type GetV1NameGetProjectMappingXgafvEnum string

const (
	GetV1NameGetProjectMappingXgafvEnum1 GetV1NameGetProjectMappingXgafvEnum = "1"
	GetV1NameGetProjectMappingXgafvEnum2 GetV1NameGetProjectMappingXgafvEnum = "2"
)
