// Code generated by Sideko (sideko.dev)
package types

type GetV1ResourceGetIamPolicyXgafvEnum string

const (
	GetV1ResourceGetIamPolicyXgafvEnum1 GetV1ResourceGetIamPolicyXgafvEnum = "1"
	GetV1ResourceGetIamPolicyXgafvEnum2 GetV1ResourceGetIamPolicyXgafvEnum = "2"
)
