// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesTypeNameAltEnum string

const (
	GetV1ParentResourcefilesTypeNameAltEnumJson  GetV1ParentResourcefilesTypeNameAltEnum = "json"
	GetV1ParentResourcefilesTypeNameAltEnumMedia GetV1ParentResourcefilesTypeNameAltEnum = "media"
	GetV1ParentResourcefilesTypeNameAltEnumProto GetV1ParentResourcefilesTypeNameAltEnum = "proto"
)
