// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityIncidentsXgafvEnum string

const (
	GetV1ParentSecurityIncidentsXgafvEnum1 GetV1ParentSecurityIncidentsXgafvEnum = "1"
	GetV1ParentSecurityIncidentsXgafvEnum2 GetV1ParentSecurityIncidentsXgafvEnum = "2"
)
