// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentNatAddressesAltEnum string

const (
	GetV1ParentNatAddressesAltEnumJson  GetV1ParentNatAddressesAltEnum = "json"
	GetV1ParentNatAddressesAltEnumMedia GetV1ParentNatAddressesAltEnum = "media"
	GetV1ParentNatAddressesAltEnumProto GetV1ParentNatAddressesAltEnum = "proto"
)
