// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAnalyticsExportsAltEnum string

const (
	GetV1ParentAnalyticsExportsAltEnumJson  GetV1ParentAnalyticsExportsAltEnum = "json"
	GetV1ParentAnalyticsExportsAltEnumMedia GetV1ParentAnalyticsExportsAltEnum = "media"
	GetV1ParentAnalyticsExportsAltEnumProto GetV1ParentAnalyticsExportsAltEnum = "proto"
)
