// Code generated by Sideko (sideko.dev)
package types

type GetV1NameAltEnum string

const (
	GetV1NameAltEnumJson  GetV1NameAltEnum = "json"
	GetV1NameAltEnumMedia GetV1NameAltEnum = "media"
	GetV1NameAltEnumProto GetV1NameAltEnum = "proto"
)
