// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityReportsAltEnum string

const (
	GetV1ParentSecurityReportsAltEnumJson  GetV1ParentSecurityReportsAltEnum = "json"
	GetV1ParentSecurityReportsAltEnumMedia GetV1ParentSecurityReportsAltEnum = "media"
	GetV1ParentSecurityReportsAltEnumProto GetV1ParentSecurityReportsAltEnum = "proto"
)
