// Code generated by Sideko (sideko.dev)
package types

type GetV1NameCsrAltEnum string

const (
	GetV1NameCsrAltEnumJson  GetV1NameCsrAltEnum = "json"
	GetV1NameCsrAltEnumMedia GetV1NameCsrAltEnum = "media"
	GetV1NameCsrAltEnumProto GetV1NameCsrAltEnum = "proto"
)
