// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentResourcefilesTypeNameXgafvEnum string

const (
	GetV1ParentResourcefilesTypeNameXgafvEnum1 GetV1ParentResourcefilesTypeNameXgafvEnum = "1"
	GetV1ParentResourcefilesTypeNameXgafvEnum2 GetV1ParentResourcefilesTypeNameXgafvEnum = "2"
)
