// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentOverridesAltEnum string

const (
	GetV1ParentOverridesAltEnumJson  GetV1ParentOverridesAltEnum = "json"
	GetV1ParentOverridesAltEnumMedia GetV1ParentOverridesAltEnum = "media"
	GetV1ParentOverridesAltEnumProto GetV1ParentOverridesAltEnum = "proto"
)
