// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentNatAddressesXgafvEnum string

const (
	GetV1ParentNatAddressesXgafvEnum1 GetV1ParentNatAddressesXgafvEnum = "1"
	GetV1ParentNatAddressesXgafvEnum2 GetV1ParentNatAddressesXgafvEnum = "2"
)
