// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityProfilesXgafvEnum string

const (
	GetV1ParentSecurityProfilesXgafvEnum1 GetV1ParentSecurityProfilesXgafvEnum = "1"
	GetV1ParentSecurityProfilesXgafvEnum2 GetV1ParentSecurityProfilesXgafvEnum = "2"
)
