// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentDebugsessionsAltEnum string

const (
	GetV1ParentDebugsessionsAltEnumJson  GetV1ParentDebugsessionsAltEnum = "json"
	GetV1ParentDebugsessionsAltEnumMedia GetV1ParentDebugsessionsAltEnum = "media"
	GetV1ParentDebugsessionsAltEnumProto GetV1ParentDebugsessionsAltEnum = "proto"
)
