// Code generated by Sideko (sideko.dev)
package types

type GetV1NameListRevisionsXgafvEnum string

const (
	GetV1NameListRevisionsXgafvEnum1 GetV1NameListRevisionsXgafvEnum = "1"
	GetV1NameListRevisionsXgafvEnum2 GetV1NameListRevisionsXgafvEnum = "2"
)
