// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentAltEnum string

const (
	GetV1ParentAltEnumJson  GetV1ParentAltEnum = "json"
	GetV1ParentAltEnumMedia GetV1ParentAltEnum = "media"
	GetV1ParentAltEnumProto GetV1ParentAltEnum = "proto"
)
