// Code generated by Sideko (sideko.dev)
package types

type GetV1ParentSecurityReportsXgafvEnum string

const (
	GetV1ParentSecurityReportsXgafvEnum1 GetV1ParentSecurityReportsXgafvEnum = "1"
	GetV1ParentSecurityReportsXgafvEnum2 GetV1ParentSecurityReportsXgafvEnum = "2"
)
