// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ExportRequest struct {
	CsvDelimiter  nullable.Nullable[string]                       `json:"csvDelimiter,omitempty"`
	DatastoreName nullable.Nullable[string]                       `json:"datastoreName,omitempty"`
	DateRange     nullable.Nullable[GoogleCloudApigeeV1DateRange] `json:"dateRange,omitempty"`
	Description   nullable.Nullable[string]                       `json:"description,omitempty"`
	Name          nullable.Nullable[string]                       `json:"name,omitempty"`
	OutputFormat  nullable.Nullable[string]                       `json:"outputFormat,omitempty"`
}
