// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleIamV1Policy struct {
	AuditConfigs nullable.Nullable[[]GoogleIamV1AuditConfig] `json:"auditConfigs,omitempty"`
	Bindings     nullable.Nullable[[]GoogleIamV1Binding]     `json:"bindings,omitempty"`
	Etag         nullable.Nullable[string]                   `json:"etag,omitempty"`
	Version      nullable.Nullable[int]                      `json:"version,omitempty"`
}
