// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Certificate struct {
	CertInfo nullable.Nullable[[]GoogleCloudApigeeV1CertInfo] `json:"certInfo,omitempty"`
}
