// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1CertInfo struct {
	BasicConstraints        nullable.Nullable[string]   `json:"basicConstraints,omitempty"`
	ExpiryDate              nullable.Nullable[string]   `json:"expiryDate,omitempty"`
	IsValid                 nullable.Nullable[string]   `json:"isValid,omitempty"`
	Issuer                  nullable.Nullable[string]   `json:"issuer,omitempty"`
	PublicKey               nullable.Nullable[string]   `json:"publicKey,omitempty"`
	SerialNumber            nullable.Nullable[string]   `json:"serialNumber,omitempty"`
	SigAlgName              nullable.Nullable[string]   `json:"sigAlgName,omitempty"`
	Subject                 nullable.Nullable[string]   `json:"subject,omitempty"`
	SubjectAlternativeNames nullable.Nullable[[]string] `json:"subjectAlternativeNames,omitempty"`
	ValidFrom               nullable.Nullable[string]   `json:"validFrom,omitempty"`
	Version                 nullable.Nullable[int]      `json:"version,omitempty"`
}
