// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Operation struct {
	Methods  nullable.Nullable[[]string] `json:"methods,omitempty"`
	Resource nullable.Nullable[string]   `json:"resource,omitempty"`
}
