// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityIncident struct {
	DetectionTypes    nullable.Nullable[[]string]                                         `json:"detectionTypes,omitempty"`
	DisplayName       nullable.Nullable[string]                                           `json:"displayName,omitempty"`
	FirstDetectedTime nullable.Nullable[string]                                           `json:"firstDetectedTime,omitempty"`
	LastDetectedTime  nullable.Nullable[string]                                           `json:"lastDetectedTime,omitempty"`
	Name              nullable.Nullable[string]                                           `json:"name,omitempty"`
	RiskLevel         nullable.Nullable[GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum] `json:"riskLevel,omitempty"`
	TrafficCount      nullable.Nullable[string]                                           `json:"trafficCount,omitempty"`
}
