// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListDatastoresResponse struct {
	Datastores nullable.Nullable[[]GoogleCloudApigeeV1Datastore] `json:"datastores,omitempty"`
}
