// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1EndpointAttachmentStateEnum string

const (
	GoogleCloudApigeeV1EndpointAttachmentStateEnumActive           GoogleCloudApigeeV1EndpointAttachmentStateEnum = "ACTIVE"
	GoogleCloudApigeeV1EndpointAttachmentStateEnumCreating         GoogleCloudApigeeV1EndpointAttachmentStateEnum = "CREATING"
	GoogleCloudApigeeV1EndpointAttachmentStateEnumDeleting         GoogleCloudApigeeV1EndpointAttachmentStateEnum = "DELETING"
	GoogleCloudApigeeV1EndpointAttachmentStateEnumStateUnspecified GoogleCloudApigeeV1EndpointAttachmentStateEnum = "STATE_UNSPECIFIED"
	GoogleCloudApigeeV1EndpointAttachmentStateEnumUpdating         GoogleCloudApigeeV1EndpointAttachmentStateEnum = "UPDATING"
)
