// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeploymentChangeReport struct {
	RoutingChanges   nullable.Nullable[[]GoogleCloudApigeeV1DeploymentChangeReportRoutingChange]   `json:"routingChanges,omitempty"`
	RoutingConflicts nullable.Nullable[[]GoogleCloudApigeeV1DeploymentChangeReportRoutingConflict] `json:"routingConflicts,omitempty"`
	ValidationErrors nullable.Nullable[GoogleRpcPreconditionFailure]                               `json:"validationErrors,omitempty"`
}
