// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DataCollector struct {
	CreatedAt      nullable.Nullable[string]                                   `json:"createdAt,omitempty"`
	Description    nullable.Nullable[string]                                   `json:"description,omitempty"`
	LastModifiedAt nullable.Nullable[string]                                   `json:"lastModifiedAt,omitempty"`
	Name           nullable.Nullable[string]                                   `json:"name,omitempty"`
	Type           nullable.Nullable[GoogleCloudApigeeV1DataCollectorTypeEnum] `json:"type,omitempty"`
}
