// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1OrganizationProjectMapping struct {
	Location     nullable.Nullable[string]   `json:"location,omitempty"`
	Organization nullable.Nullable[string]   `json:"organization,omitempty"`
	ProjectId    nullable.Nullable[string]   `json:"projectId,omitempty"`
	ProjectIds   nullable.Nullable[[]string] `json:"projectIds,omitempty"`
}
