// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleIamV1Binding struct {
	Condition nullable.Nullable[GoogleTypeExpr] `json:"condition,omitempty"`
	Members   nullable.Nullable[[]string]       `json:"members,omitempty"`
	Role      nullable.Nullable[string]         `json:"role,omitempty"`
}
