// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ScoreComponent struct {
	CalculateTime   nullable.Nullable[string]                                            `json:"calculateTime,omitempty"`
	DataCaptureTime nullable.Nullable[string]                                            `json:"dataCaptureTime,omitempty"`
	DrilldownPaths  nullable.Nullable[[]string]                                          `json:"drilldownPaths,omitempty"`
	Recommendations nullable.Nullable[[]GoogleCloudApigeeV1ScoreComponentRecommendation] `json:"recommendations,omitempty"`
	Score           nullable.Nullable[int]                                               `json:"score,omitempty"`
	ScorePath       nullable.Nullable[string]                                            `json:"scorePath,omitempty"`
}
