// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1ApiProxyApiProxyTypeEnum string

const (
	GoogleCloudApigeeV1ApiProxyApiProxyTypeEnumApiProxyTypeUnspecified GoogleCloudApigeeV1ApiProxyApiProxyTypeEnum = "API_PROXY_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1ApiProxyApiProxyTypeEnumConfigurable            GoogleCloudApigeeV1ApiProxyApiProxyTypeEnum = "CONFIGURABLE"
	GoogleCloudApigeeV1ApiProxyApiProxyTypeEnumProgrammable            GoogleCloudApigeeV1ApiProxyApiProxyTypeEnum = "PROGRAMMABLE"
)
