// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1OrganizationSubscriptionTypeEnum string

const (
	GoogleCloudApigeeV1OrganizationSubscriptionTypeEnumPaid                        GoogleCloudApigeeV1OrganizationSubscriptionTypeEnum = "PAID"
	GoogleCloudApigeeV1OrganizationSubscriptionTypeEnumSubscriptionTypeUnspecified GoogleCloudApigeeV1OrganizationSubscriptionTypeEnum = "SUBSCRIPTION_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1OrganizationSubscriptionTypeEnumTrial                       GoogleCloudApigeeV1OrganizationSubscriptionTypeEnum = "TRIAL"
)
