// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListInstancesResponse struct {
	Instances     nullable.Nullable[[]GoogleCloudApigeeV1Instance] `json:"instances,omitempty"`
	NextPageToken nullable.Nullable[string]                        `json:"nextPageToken,omitempty"`
}
