// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeveloperBalance struct {
	Wallets nullable.Nullable[[]GoogleCloudApigeeV1DeveloperBalanceWallet] `json:"wallets,omitempty"`
}
