// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1GraphQlOperation struct {
	Operation      nullable.Nullable[string]   `json:"operation,omitempty"`
	OperationTypes nullable.Nullable[[]string] `json:"operationTypes,omitempty"`
}
