// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleRpcPreconditionFailure struct {
	Violations nullable.Nullable[[]GoogleRpcPreconditionFailureViolation] `json:"violations,omitempty"`
}
