// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleIamV1SetIamPolicyRequest struct {
	Policy     nullable.Nullable[GoogleIamV1Policy] `json:"policy,omitempty"`
	UpdateMask nullable.Nullable[string]            `json:"updateMask,omitempty"`
}
