// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1CreditDeveloperBalanceRequest struct {
	TransactionAmount nullable.Nullable[GoogleTypeMoney] `json:"transactionAmount,omitempty"`
	TransactionId     nullable.Nullable[string]          `json:"transactionId,omitempty"`
}
