// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ConnectorsPlatformConfig struct {
	Enabled   nullable.Nullable[bool]   `json:"enabled,omitempty"`
	ExpiresAt nullable.Nullable[string] `json:"expiresAt,omitempty"`
}
