// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeploymentChangeReportRoutingConflict struct {
	ConflictingDeployment nullable.Nullable[GoogleCloudApigeeV1DeploymentChangeReportRoutingDeployment] `json:"conflictingDeployment,omitempty"`
	Description           nullable.Nullable[string]                                                     `json:"description,omitempty"`
	EnvironmentGroup      nullable.Nullable[string]                                                     `json:"environmentGroup,omitempty"`
}
