// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityProfile struct {
	DisplayName         nullable.Nullable[string]                                            `json:"displayName,omitempty"`
	Environments        nullable.Nullable[[]GoogleCloudApigeeV1SecurityProfileEnvironment]   `json:"environments,omitempty"`
	MaxScore            nullable.Nullable[int]                                               `json:"maxScore,omitempty"`
	MinScore            nullable.Nullable[int]                                               `json:"minScore,omitempty"`
	Name                nullable.Nullable[string]                                            `json:"name,omitempty"`
	RevisionCreateTime  nullable.Nullable[string]                                            `json:"revisionCreateTime,omitempty"`
	RevisionId          nullable.Nullable[string]                                            `json:"revisionId,omitempty"`
	RevisionPublishTime nullable.Nullable[string]                                            `json:"revisionPublishTime,omitempty"`
	RevisionUpdateTime  nullable.Nullable[string]                                            `json:"revisionUpdateTime,omitempty"`
	ScoringConfigs      nullable.Nullable[[]GoogleCloudApigeeV1SecurityProfileScoringConfig] `json:"scoringConfigs,omitempty"`
}
