// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListArchiveDeploymentsResponse struct {
	ArchiveDeployments nullable.Nullable[[]GoogleCloudApigeeV1ArchiveDeployment] `json:"archiveDeployments,omitempty"`
	NextPageToken      nullable.Nullable[string]                                 `json:"nextPageToken,omitempty"`
}
