// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Keystore struct {
	Aliases nullable.Nullable[[]string] `json:"aliases,omitempty"`
	Name    nullable.Nullable[string]   `json:"name,omitempty"`
}
