// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeploymentChangeReportRoutingChange struct {
	Description           nullable.Nullable[string]                                                     `json:"description,omitempty"`
	EnvironmentGroup      nullable.Nullable[string]                                                     `json:"environmentGroup,omitempty"`
	FromDeployment        nullable.Nullable[GoogleCloudApigeeV1DeploymentChangeReportRoutingDeployment] `json:"fromDeployment,omitempty"`
	ShouldSequenceRollout nullable.Nullable[bool]                                                       `json:"shouldSequenceRollout,omitempty"`
	ToDeployment          nullable.Nullable[GoogleCloudApigeeV1DeploymentChangeReportRoutingDeployment] `json:"toDeployment,omitempty"`
}
