// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ScoreComponentRecommendationAction struct {
	ActionContext nullable.Nullable[GoogleCloudApigeeV1ScoreComponentRecommendationActionActionContext] `json:"actionContext,omitempty"`
	Description   nullable.Nullable[string]                                                             `json:"description,omitempty"`
}
