// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Properties struct {
	Property nullable.Nullable[[]GoogleCloudApigeeV1Property] `json:"property,omitempty"`
}
