// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleIamV1AuditLogConfig struct {
	ExemptedMembers nullable.Nullable[[]string]                             `json:"exemptedMembers,omitempty"`
	LogType         nullable.Nullable[GoogleIamV1AuditLogConfigLogTypeEnum] `json:"logType,omitempty"`
}
