// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Instance struct {
	ConsumerAcceptList    nullable.Nullable[[]string]                                        `json:"consumerAcceptList,omitempty"`
	CreatedAt             nullable.Nullable[string]                                          `json:"createdAt,omitempty"`
	Description           nullable.Nullable[string]                                          `json:"description,omitempty"`
	DiskEncryptionKeyName nullable.Nullable[string]                                          `json:"diskEncryptionKeyName,omitempty"`
	DisplayName           nullable.Nullable[string]                                          `json:"displayName,omitempty"`
	Host                  nullable.Nullable[string]                                          `json:"host,omitempty"`
	IpRange               nullable.Nullable[string]                                          `json:"ipRange,omitempty"`
	LastModifiedAt        nullable.Nullable[string]                                          `json:"lastModifiedAt,omitempty"`
	Location              nullable.Nullable[string]                                          `json:"location,omitempty"`
	Name                  nullable.Nullable[string]                                          `json:"name,omitempty"`
	PeeringCidrRange      nullable.Nullable[GoogleCloudApigeeV1InstancePeeringCidrRangeEnum] `json:"peeringCidrRange,omitempty"`
	Port                  nullable.Nullable[string]                                          `json:"port,omitempty"`
	RuntimeVersion        nullable.Nullable[string]                                          `json:"runtimeVersion,omitempty"`
	ServiceAttachment     nullable.Nullable[string]                                          `json:"serviceAttachment,omitempty"`
	State                 nullable.Nullable[GoogleCloudApigeeV1InstanceStateEnum]            `json:"state,omitempty"`
}
