// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Attributes struct {
	Attribute nullable.Nullable[[]GoogleCloudApigeeV1Attribute] `json:"attribute,omitempty"`
}
