// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TargetServer struct {
	Description nullable.Nullable[string]                                      `json:"description,omitempty"`
	Host        nullable.Nullable[string]                                      `json:"host,omitempty"`
	IsEnabled   nullable.Nullable[bool]                                        `json:"isEnabled,omitempty"`
	Name        nullable.Nullable[string]                                      `json:"name,omitempty"`
	Port        nullable.Nullable[int]                                         `json:"port,omitempty"`
	Protocol    nullable.Nullable[GoogleCloudApigeeV1TargetServerProtocolEnum] `json:"protocol,omitempty"`
	SSlInfo     nullable.Nullable[GoogleCloudApigeeV1TlsInfo]                  `json:"sSLInfo,omitempty"`
}
