// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListRatePlansResponse struct {
	NextStartKey nullable.Nullable[string]                        `json:"nextStartKey,omitempty"`
	RatePlans    nullable.Nullable[[]GoogleCloudApigeeV1RatePlan] `json:"ratePlans,omitempty"`
}
