// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1InstanceDeploymentStatus struct {
	DeployedRevisions nullable.Nullable[[]GoogleCloudApigeeV1InstanceDeploymentStatusDeployedRevision] `json:"deployedRevisions,omitempty"`
	DeployedRoutes    nullable.Nullable[[]GoogleCloudApigeeV1InstanceDeploymentStatusDeployedRoute]    `json:"deployedRoutes,omitempty"`
	Instance          nullable.Nullable[string]                                                        `json:"instance,omitempty"`
}
