// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListSecurityProfilesResponse struct {
	NextPageToken    nullable.Nullable[string]                               `json:"nextPageToken,omitempty"`
	SecurityProfiles nullable.Nullable[[]GoogleCloudApigeeV1SecurityProfile] `json:"securityProfiles,omitempty"`
}
