// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1EnvironmentGroup struct {
	CreatedAt      nullable.Nullable[string]                                       `json:"createdAt,omitempty"`
	Hostnames      nullable.Nullable[[]string]                                     `json:"hostnames,omitempty"`
	LastModifiedAt nullable.Nullable[string]                                       `json:"lastModifiedAt,omitempty"`
	Name           nullable.Nullable[string]                                       `json:"name,omitempty"`
	State          nullable.Nullable[GoogleCloudApigeeV1EnvironmentGroupStateEnum] `json:"state,omitempty"`
}
