// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleIamV1TestIamPermissionsResponse struct {
	Permissions nullable.Nullable[[]string] `json:"permissions,omitempty"`
}
