// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ConfigVersion struct {
	MajorVersion nullable.Nullable[int] `json:"majorVersion,omitempty"`
	MinorVersion nullable.Nullable[int] `json:"minorVersion,omitempty"`
}
