// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ScoreComponentRecommendation struct {
	Actions     nullable.Nullable[[]GoogleCloudApigeeV1ScoreComponentRecommendationAction] `json:"actions,omitempty"`
	Description nullable.Nullable[string]                                                  `json:"description,omitempty"`
	Impact      nullable.Nullable[int]                                                     `json:"impact,omitempty"`
	Title       nullable.Nullable[string]                                                  `json:"title,omitempty"`
}
