// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListDeveloperSubscriptionsResponse struct {
	DeveloperSubscriptions nullable.Nullable[[]GoogleCloudApigeeV1DeveloperSubscription] `json:"developerSubscriptions,omitempty"`
	NextStartKey           nullable.Nullable[string]                                     `json:"nextStartKey,omitempty"`
}
