// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Export struct {
	Created       nullable.Nullable[string] `json:"created,omitempty"`
	DatastoreName nullable.Nullable[string] `json:"datastoreName,omitempty"`
	Description   nullable.Nullable[string] `json:"description,omitempty"`
	Error         nullable.Nullable[string] `json:"error,omitempty"`
	ExecutionTime nullable.Nullable[string] `json:"executionTime,omitempty"`
	Name          nullable.Nullable[string] `json:"name,omitempty"`
	Self          nullable.Nullable[string] `json:"self,omitempty"`
	State         nullable.Nullable[string] `json:"state,omitempty"`
	Updated       nullable.Nullable[string] `json:"updated,omitempty"`
}
