// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1KeyValueEntry struct {
	Name  nullable.Nullable[string] `json:"name,omitempty"`
	Value nullable.Nullable[string] `json:"value,omitempty"`
}
