// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1InstancePeeringCidrRangeEnum string

const (
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumCidrRangeUnspecified GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "CIDR_RANGE_UNSPECIFIED"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash16              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_16"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash17              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_17"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash18              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_18"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash19              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_19"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash20              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_20"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash22              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_22"
	GoogleCloudApigeeV1InstancePeeringCidrRangeEnumSlash23              GoogleCloudApigeeV1InstancePeeringCidrRangeEnum = "SLASH_23"
)
