// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1DeploymentStateEnum string

const (
	GoogleCloudApigeeV1DeploymentStateEnumError                   GoogleCloudApigeeV1DeploymentStateEnum = "ERROR"
	GoogleCloudApigeeV1DeploymentStateEnumProgressing             GoogleCloudApigeeV1DeploymentStateEnum = "PROGRESSING"
	GoogleCloudApigeeV1DeploymentStateEnumReady                   GoogleCloudApigeeV1DeploymentStateEnum = "READY"
	GoogleCloudApigeeV1DeploymentStateEnumRuntimeStateUnspecified GoogleCloudApigeeV1DeploymentStateEnum = "RUNTIME_STATE_UNSPECIFIED"
)
