// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1QueryMetric struct {
	Alias    nullable.Nullable[string] `json:"alias,omitempty"`
	Function nullable.Nullable[string] `json:"function,omitempty"`
	Name     nullable.Nullable[string] `json:"name,omitempty"`
	Operator nullable.Nullable[string] `json:"operator,omitempty"`
	Value    nullable.Nullable[string] `json:"value,omitempty"`
}
