// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnum string

const (
	GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnumOperation                    GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnum = "OPERATION"
	GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnumProxy                        GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnum = "PROXY"
	GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnumQuotaCounterScopeUnspecified GoogleCloudApigeeV1ApiProductQuotaCounterScopeEnum = "QUOTA_COUNTER_SCOPE_UNSPECIFIED"
)
