// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1OrganizationRuntimeTypeEnum string

const (
	GoogleCloudApigeeV1OrganizationRuntimeTypeEnumCloud                  GoogleCloudApigeeV1OrganizationRuntimeTypeEnum = "CLOUD"
	GoogleCloudApigeeV1OrganizationRuntimeTypeEnumHybrid                 GoogleCloudApigeeV1OrganizationRuntimeTypeEnum = "HYBRID"
	GoogleCloudApigeeV1OrganizationRuntimeTypeEnumRuntimeTypeUnspecified GoogleCloudApigeeV1OrganizationRuntimeTypeEnum = "RUNTIME_TYPE_UNSPECIFIED"
)
