// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SyncAuthorization struct {
	Etag       nullable.Nullable[string]   `json:"etag,omitempty"`
	Identities nullable.Nullable[[]string] `json:"identities,omitempty"`
}
