// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TestDatastoreResponse struct {
	Error nullable.Nullable[string] `json:"error,omitempty"`
	State nullable.Nullable[string] `json:"state,omitempty"`
}
