// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SetAddonsRequest struct {
	AddonsConfig nullable.Nullable[GoogleCloudApigeeV1AddonsConfig] `json:"addonsConfig,omitempty"`
}
