// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityProfileScoringConfig struct {
	Description nullable.Nullable[string] `json:"description,omitempty"`
	ScorePath   nullable.Nullable[string] `json:"scorePath,omitempty"`
	Title       nullable.Nullable[string] `json:"title,omitempty"`
}
