// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DatastoreConfig struct {
	BucketName  nullable.Nullable[string] `json:"bucketName,omitempty"`
	DatasetName nullable.Nullable[string] `json:"datasetName,omitempty"`
	Path        nullable.Nullable[string] `json:"path,omitempty"`
	ProjectId   nullable.Nullable[string] `json:"projectId,omitempty"`
	TablePrefix nullable.Nullable[string] `json:"tablePrefix,omitempty"`
}
