// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Query struct {
	CsvDelimiter       nullable.Nullable[string]                           `json:"csvDelimiter,omitempty"`
	Dimensions         nullable.Nullable[[]string]                         `json:"dimensions,omitempty"`
	EnvgroupHostname   nullable.Nullable[string]                           `json:"envgroupHostname,omitempty"`
	Filter             nullable.Nullable[string]                           `json:"filter,omitempty"`
	GroupByTimeUnit    nullable.Nullable[string]                           `json:"groupByTimeUnit,omitempty"`
	Limit              nullable.Nullable[int]                              `json:"limit,omitempty"`
	Metrics            nullable.Nullable[[]GoogleCloudApigeeV1QueryMetric] `json:"metrics,omitempty"`
	Name               nullable.Nullable[string]                           `json:"name,omitempty"`
	OutputFormat       nullable.Nullable[string]                           `json:"outputFormat,omitempty"`
	ReportDefinitionId nullable.Nullable[string]                           `json:"reportDefinitionId,omitempty"`
	TimeRange          nullable.Nullable[interface{}]                      `json:"timeRange,omitempty"`
}
