// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SharedFlow struct {
	LatestRevisionId nullable.Nullable[string]                            `json:"latestRevisionId,omitempty"`
	MetaData         nullable.Nullable[GoogleCloudApigeeV1EntityMetadata] `json:"metaData,omitempty"`
	Name             nullable.Nullable[string]                            `json:"name,omitempty"`
	Revision         nullable.Nullable[[]string]                          `json:"revision,omitempty"`
}
