// Code generated by Sideko (sideko.dev)
package types

type GoogleIamV1AuditLogConfigLogTypeEnum string

const (
	GoogleIamV1AuditLogConfigLogTypeEnumAdminRead          GoogleIamV1AuditLogConfigLogTypeEnum = "ADMIN_READ"
	GoogleIamV1AuditLogConfigLogTypeEnumDataRead           GoogleIamV1AuditLogConfigLogTypeEnum = "DATA_READ"
	GoogleIamV1AuditLogConfigLogTypeEnumDataWrite          GoogleIamV1AuditLogConfigLogTypeEnum = "DATA_WRITE"
	GoogleIamV1AuditLogConfigLogTypeEnumLogTypeUnspecified GoogleIamV1AuditLogConfigLogTypeEnum = "LOG_TYPE_UNSPECIFIED"
)
