// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityProfileEnvironment struct {
	AttachTime  nullable.Nullable[string] `json:"attachTime,omitempty"`
	Environment nullable.Nullable[string] `json:"environment,omitempty"`
}
