// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Deployment struct {
	ApiProxy        nullable.Nullable[string]                                                     `json:"apiProxy,omitempty"`
	DeployStartTime nullable.Nullable[string]                                                     `json:"deployStartTime,omitempty"`
	Environment     nullable.Nullable[string]                                                     `json:"environment,omitempty"`
	Errors          nullable.Nullable[[]GoogleRpcStatus]                                          `json:"errors,omitempty"`
	Instances       nullable.Nullable[[]GoogleCloudApigeeV1InstanceDeploymentStatus]              `json:"instances,omitempty"`
	Pods            nullable.Nullable[[]GoogleCloudApigeeV1PodStatus]                             `json:"pods,omitempty"`
	Revision        nullable.Nullable[string]                                                     `json:"revision,omitempty"`
	RouteConflicts  nullable.Nullable[[]GoogleCloudApigeeV1DeploymentChangeReportRoutingConflict] `json:"routeConflicts,omitempty"`
	ServiceAccount  nullable.Nullable[string]                                                     `json:"serviceAccount,omitempty"`
	State           nullable.Nullable[GoogleCloudApigeeV1DeploymentStateEnum]                     `json:"state,omitempty"`
}
