// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TraceConfigOverride struct {
	ApiProxy       nullable.Nullable[string]                                 `json:"apiProxy,omitempty"`
	Name           nullable.Nullable[string]                                 `json:"name,omitempty"`
	SamplingConfig nullable.Nullable[GoogleCloudApigeeV1TraceSamplingConfig] `json:"samplingConfig,omitempty"`
}
