// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeveloperBalanceWallet struct {
	Balance        nullable.Nullable[GoogleTypeMoney] `json:"balance,omitempty"`
	LastCreditTime nullable.Nullable[string]          `json:"lastCreditTime,omitempty"`
}
