// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ResourceFile struct {
	Name nullable.Nullable[string] `json:"name,omitempty"`
	Type nullable.Nullable[string] `json:"type,omitempty"`
}
