// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1QueryTimeSeriesStatsRequest struct {
	Dimensions     nullable.Nullable[[]string]                                                         `json:"dimensions,omitempty"`
	Filter         nullable.Nullable[string]                                                           `json:"filter,omitempty"`
	Metrics        nullable.Nullable[[]GoogleCloudApigeeV1MetricAggregation]                           `json:"metrics,omitempty"`
	PageSize       nullable.Nullable[int]                                                              `json:"pageSize,omitempty"`
	PageToken      nullable.Nullable[string]                                                           `json:"pageToken,omitempty"`
	TimeRange      nullable.Nullable[GoogleTypeInterval]                                               `json:"timeRange,omitempty"`
	TimestampOrder nullable.Nullable[GoogleCloudApigeeV1QueryTimeSeriesStatsRequestTimestampOrderEnum] `json:"timestampOrder,omitempty"`
	WindowSize     nullable.Nullable[GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum]     `json:"windowSize,omitempty"`
}
