// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListAsyncQueriesResponse struct {
	Queries nullable.Nullable[[]GoogleCloudApigeeV1AsyncQuery] `json:"queries,omitempty"`
}
