// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Score struct {
	Component     nullable.Nullable[GoogleCloudApigeeV1ScoreComponent]   `json:"component,omitempty"`
	Subcomponents nullable.Nullable[[]GoogleCloudApigeeV1ScoreComponent] `json:"subcomponents,omitempty"`
	TimeRange     nullable.Nullable[GoogleTypeInterval]                  `json:"timeRange,omitempty"`
}
