// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityReportQueryMetric struct {
	AggregationFunction nullable.Nullable[string] `json:"aggregationFunction,omitempty"`
	Alias               nullable.Nullable[string] `json:"alias,omitempty"`
	Name                nullable.Nullable[string] `json:"name,omitempty"`
	Operator            nullable.Nullable[string] `json:"operator,omitempty"`
	Value               nullable.Nullable[string] `json:"value,omitempty"`
}
