// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Session struct {
	Id          nullable.Nullable[string] `json:"id,omitempty"`
	TimestampMs nullable.Nullable[string] `json:"timestampMs,omitempty"`
}
