// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ApiProxy struct {
	ApiProxyType     nullable.Nullable[GoogleCloudApigeeV1ApiProxyApiProxyTypeEnum] `json:"apiProxyType,omitempty"`
	Labels           nullable.Nullable[GoogleCloudApigeeV1ApiProxyLabels]           `json:"labels,omitempty"`
	LatestRevisionId nullable.Nullable[string]                                      `json:"latestRevisionId,omitempty"`
	MetaData         nullable.Nullable[GoogleCloudApigeeV1EntityMetadata]           `json:"metaData,omitempty"`
	Name             nullable.Nullable[string]                                      `json:"name,omitempty"`
	ReadOnly         nullable.Nullable[bool]                                        `json:"readOnly,omitempty"`
	Revision         nullable.Nullable[[]string]                                    `json:"revision,omitempty"`
}
