// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ComputeEnvironmentScoresRequestFilter struct {
	ScorePath nullable.Nullable[string] `json:"scorePath,omitempty"`
}
