// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleTypeExpr struct {
	Description nullable.Nullable[string] `json:"description,omitempty"`
	Expression  nullable.Nullable[string] `json:"expression,omitempty"`
	Location    nullable.Nullable[string] `json:"location,omitempty"`
	Title       nullable.Nullable[string] `json:"title,omitempty"`
}
