// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TraceSamplingConfig struct {
	Sampler      nullable.Nullable[GoogleCloudApigeeV1TraceSamplingConfigSamplerEnum] `json:"sampler,omitempty"`
	SamplingRate nullable.Nullable[float64]                                           `json:"samplingRate,omitempty"`
}
