// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeploymentChangeReportRoutingDeployment struct {
	ApiProxy    nullable.Nullable[string] `json:"apiProxy,omitempty"`
	Basepath    nullable.Nullable[string] `json:"basepath,omitempty"`
	Environment nullable.Nullable[string] `json:"environment,omitempty"`
	Revision    nullable.Nullable[string] `json:"revision,omitempty"`
}
