// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ComputeEnvironmentScoresResponse struct {
	NextPageToken nullable.Nullable[string]                     `json:"nextPageToken,omitempty"`
	Scores        nullable.Nullable[[]GoogleCloudApigeeV1Score] `json:"scores,omitempty"`
}
