// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TlsInfo struct {
	Ciphers                nullable.Nullable[[]string]                             `json:"ciphers,omitempty"`
	ClientAuthEnabled      nullable.Nullable[bool]                                 `json:"clientAuthEnabled,omitempty"`
	CommonName             nullable.Nullable[GoogleCloudApigeeV1TlsInfoCommonName] `json:"commonName,omitempty"`
	Enabled                nullable.Nullable[bool]                                 `json:"enabled,omitempty"`
	IgnoreValidationErrors nullable.Nullable[bool]                                 `json:"ignoreValidationErrors,omitempty"`
	KeyAlias               nullable.Nullable[string]                               `json:"keyAlias,omitempty"`
	KeyStore               nullable.Nullable[string]                               `json:"keyStore,omitempty"`
	Protocols              nullable.Nullable[[]string]                             `json:"protocols,omitempty"`
	TrustStore             nullable.Nullable[string]                               `json:"trustStore,omitempty"`
}
