// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListExportsResponse struct {
	Exports nullable.Nullable[[]GoogleCloudApigeeV1Export] `json:"exports,omitempty"`
}
