// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1InstanceDeploymentStatusDeployedRoute struct {
	Basepath    nullable.Nullable[string] `json:"basepath,omitempty"`
	Envgroup    nullable.Nullable[string] `json:"envgroup,omitempty"`
	Environment nullable.Nullable[string] `json:"environment,omitempty"`
	Percentage  nullable.Nullable[int]    `json:"percentage,omitempty"`
}
