// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1MetricAggregation struct {
	Aggregation nullable.Nullable[GoogleCloudApigeeV1MetricAggregationAggregationEnum] `json:"aggregation,omitempty"`
	Name        nullable.Nullable[string]                                              `json:"name,omitempty"`
	Order       nullable.Nullable[GoogleCloudApigeeV1MetricAggregationOrderEnum]       `json:"order,omitempty"`
}
