// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1TargetServerProtocolEnum string

const (
	GoogleCloudApigeeV1TargetServerProtocolEnumGrpc                GoogleCloudApigeeV1TargetServerProtocolEnum = "GRPC"
	GoogleCloudApigeeV1TargetServerProtocolEnumHttp                GoogleCloudApigeeV1TargetServerProtocolEnum = "HTTP"
	GoogleCloudApigeeV1TargetServerProtocolEnumProtocolUnspecified GoogleCloudApigeeV1TargetServerProtocolEnum = "PROTOCOL_UNSPECIFIED"
)
