// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum string

const (
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumAccepted                   GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "ACCEPTED"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumClosed                     GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "CLOSED"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumConnectionStateUnspecified GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "CONNECTION_STATE_UNSPECIFIED"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumFrozen                     GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "FROZEN"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumNeedsAttention             GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "NEEDS_ATTENTION"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumPending                    GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "PENDING"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumRejected                   GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "REJECTED"
	GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnumUnavailable                GoogleCloudApigeeV1EndpointAttachmentConnectionStateEnum = "UNAVAILABLE"
)
