// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1OperationGroup struct {
	OperationConfigType nullable.Nullable[string]                               `json:"operationConfigType,omitempty"`
	OperationConfigs    nullable.Nullable[[]GoogleCloudApigeeV1OperationConfig] `json:"operationConfigs,omitempty"`
}
