// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListDeveloperAppsResponse struct {
	App nullable.Nullable[[]GoogleCloudApigeeV1DeveloperApp] `json:"app,omitempty"`
}
