// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum string

const (
	GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnumBanded                            GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum = "BANDED"
	GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnumConsumptionPricingTypeUnspecified GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum = "CONSUMPTION_PRICING_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnumFixedPerUnit                      GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum = "FIXED_PER_UNIT"
	GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnumStairstep                         GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum = "STAIRSTEP"
	GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnumTiered                            GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum = "TIERED"
)
