// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1OrganizationBillingTypeEnum string

const (
	GoogleCloudApigeeV1OrganizationBillingTypeEnumBillingTypeUnspecified GoogleCloudApigeeV1OrganizationBillingTypeEnum = "BILLING_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1OrganizationBillingTypeEnumEvaluation             GoogleCloudApigeeV1OrganizationBillingTypeEnum = "EVALUATION"
	GoogleCloudApigeeV1OrganizationBillingTypeEnumPayg                   GoogleCloudApigeeV1OrganizationBillingTypeEnum = "PAYG"
	GoogleCloudApigeeV1OrganizationBillingTypeEnumSubscription           GoogleCloudApigeeV1OrganizationBillingTypeEnum = "SUBSCRIPTION"
)
