// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1UpdateError struct {
	Code     nullable.Nullable[GoogleCloudApigeeV1UpdateErrorCodeEnum] `json:"code,omitempty"`
	Message  nullable.Nullable[string]                                 `json:"message,omitempty"`
	Resource nullable.Nullable[string]                                 `json:"resource,omitempty"`
	Type     nullable.Nullable[string]                                 `json:"type,omitempty"`
}
