// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityReport struct {
	Created            nullable.Nullable[string]                                          `json:"created,omitempty"`
	DisplayName        nullable.Nullable[string]                                          `json:"displayName,omitempty"`
	EnvgroupHostname   nullable.Nullable[string]                                          `json:"envgroupHostname,omitempty"`
	Error              nullable.Nullable[string]                                          `json:"error,omitempty"`
	ExecutionTime      nullable.Nullable[string]                                          `json:"executionTime,omitempty"`
	QueryParams        nullable.Nullable[GoogleCloudApigeeV1SecurityReportMetadata]       `json:"queryParams,omitempty"`
	ReportDefinitionId nullable.Nullable[string]                                          `json:"reportDefinitionId,omitempty"`
	Result             nullable.Nullable[GoogleCloudApigeeV1SecurityReportResultMetadata] `json:"result,omitempty"`
	ResultFileSize     nullable.Nullable[string]                                          `json:"resultFileSize,omitempty"`
	ResultRows         nullable.Nullable[string]                                          `json:"resultRows,omitempty"`
	Self               nullable.Nullable[string]                                          `json:"self,omitempty"`
	State              nullable.Nullable[string]                                          `json:"state,omitempty"`
	Updated            nullable.Nullable[string]                                          `json:"updated,omitempty"`
}
