// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1RateRange struct {
	End   nullable.Nullable[string]          `json:"end,omitempty"`
	Fee   nullable.Nullable[GoogleTypeMoney] `json:"fee,omitempty"`
	Start nullable.Nullable[string]          `json:"start,omitempty"`
}
