// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1QueryTimeSeriesStatsResponse struct {
	Columns       nullable.Nullable[[]string]                                                  `json:"columns,omitempty"`
	NextPageToken nullable.Nullable[string]                                                    `json:"nextPageToken,omitempty"`
	Values        nullable.Nullable[[]GoogleCloudApigeeV1QueryTimeSeriesStatsResponseSequence] `json:"values,omitempty"`
}
