// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1AddonsConfig struct {
	AdvancedApiOpsConfig     nullable.Nullable[GoogleCloudApigeeV1AdvancedApiOpsConfig]     `json:"advancedApiOpsConfig,omitempty"`
	ApiSecurityConfig        nullable.Nullable[GoogleCloudApigeeV1ApiSecurityConfig]        `json:"apiSecurityConfig,omitempty"`
	ConnectorsPlatformConfig nullable.Nullable[GoogleCloudApigeeV1ConnectorsPlatformConfig] `json:"connectorsPlatformConfig,omitempty"`
	IntegrationConfig        nullable.Nullable[GoogleCloudApigeeV1IntegrationConfig]        `json:"integrationConfig,omitempty"`
	MonetizationConfig       nullable.Nullable[GoogleCloudApigeeV1MonetizationConfig]       `json:"monetizationConfig,omitempty"`
}
