// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1DataCollectorTypeEnum string

const (
	GoogleCloudApigeeV1DataCollectorTypeEnumBoolean         GoogleCloudApigeeV1DataCollectorTypeEnum = "BOOLEAN"
	GoogleCloudApigeeV1DataCollectorTypeEnumDatetime        GoogleCloudApigeeV1DataCollectorTypeEnum = "DATETIME"
	GoogleCloudApigeeV1DataCollectorTypeEnumFloat           GoogleCloudApigeeV1DataCollectorTypeEnum = "FLOAT"
	GoogleCloudApigeeV1DataCollectorTypeEnumInteger         GoogleCloudApigeeV1DataCollectorTypeEnum = "INTEGER"
	GoogleCloudApigeeV1DataCollectorTypeEnumString          GoogleCloudApigeeV1DataCollectorTypeEnum = "STRING"
	GoogleCloudApigeeV1DataCollectorTypeEnumTypeUnspecified GoogleCloudApigeeV1DataCollectorTypeEnum = "TYPE_UNSPECIFIED"
)
