// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ReportProperty struct {
	Property nullable.Nullable[string]                         `json:"property,omitempty"`
	Value    nullable.Nullable[[]GoogleCloudApigeeV1Attribute] `json:"value,omitempty"`
}
