// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1RatePlan struct {
	Apiproduct              nullable.Nullable[string]                                                `json:"apiproduct,omitempty"`
	BillingPeriod           nullable.Nullable[GoogleCloudApigeeV1RatePlanBillingPeriodEnum]          `json:"billingPeriod,omitempty"`
	ConsumptionPricingRates nullable.Nullable[[]GoogleCloudApigeeV1RateRange]                        `json:"consumptionPricingRates,omitempty"`
	ConsumptionPricingType  nullable.Nullable[GoogleCloudApigeeV1RatePlanConsumptionPricingTypeEnum] `json:"consumptionPricingType,omitempty"`
	CreatedAt               nullable.Nullable[string]                                                `json:"createdAt,omitempty"`
	CurrencyCode            nullable.Nullable[string]                                                `json:"currencyCode,omitempty"`
	Description             nullable.Nullable[string]                                                `json:"description,omitempty"`
	DisplayName             nullable.Nullable[string]                                                `json:"displayName,omitempty"`
	EndTime                 nullable.Nullable[string]                                                `json:"endTime,omitempty"`
	FixedFeeFrequency       nullable.Nullable[int]                                                   `json:"fixedFeeFrequency,omitempty"`
	FixedRecurringFee       nullable.Nullable[GoogleTypeMoney]                                       `json:"fixedRecurringFee,omitempty"`
	LastModifiedAt          nullable.Nullable[string]                                                `json:"lastModifiedAt,omitempty"`
	Name                    nullable.Nullable[string]                                                `json:"name,omitempty"`
	PaymentFundingModel     nullable.Nullable[GoogleCloudApigeeV1RatePlanPaymentFundingModelEnum]    `json:"paymentFundingModel,omitempty"`
	RevenueShareRates       nullable.Nullable[[]GoogleCloudApigeeV1RevenueShareRange]                `json:"revenueShareRates,omitempty"`
	RevenueShareType        nullable.Nullable[GoogleCloudApigeeV1RatePlanRevenueShareTypeEnum]       `json:"revenueShareType,omitempty"`
	SetupFee                nullable.Nullable[GoogleTypeMoney]                                       `json:"setupFee,omitempty"`
	StartTime               nullable.Nullable[string]                                                `json:"startTime,omitempty"`
	State                   nullable.Nullable[GoogleCloudApigeeV1RatePlanStateEnum]                  `json:"state,omitempty"`
}
