// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListCustomReportsResponse struct {
	Qualifier nullable.Nullable[[]GoogleCloudApigeeV1CustomReport] `json:"qualifier,omitempty"`
}
