// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ComputeEnvironmentScoresRequest struct {
	Filters   nullable.Nullable[[]GoogleCloudApigeeV1ComputeEnvironmentScoresRequestFilter] `json:"filters,omitempty"`
	PageSize  nullable.Nullable[int]                                                        `json:"pageSize,omitempty"`
	PageToken nullable.Nullable[string]                                                     `json:"pageToken,omitempty"`
	TimeRange nullable.Nullable[GoogleTypeInterval]                                         `json:"timeRange,omitempty"`
}
