// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityReportQuery struct {
	CsvDelimiter       nullable.Nullable[string]                                         `json:"csvDelimiter,omitempty"`
	Dimensions         nullable.Nullable[[]string]                                       `json:"dimensions,omitempty"`
	DisplayName        nullable.Nullable[string]                                         `json:"displayName,omitempty"`
	EnvgroupHostname   nullable.Nullable[string]                                         `json:"envgroupHostname,omitempty"`
	Filter             nullable.Nullable[string]                                         `json:"filter,omitempty"`
	GroupByTimeUnit    nullable.Nullable[string]                                         `json:"groupByTimeUnit,omitempty"`
	Limit              nullable.Nullable[int]                                            `json:"limit,omitempty"`
	Metrics            nullable.Nullable[[]GoogleCloudApigeeV1SecurityReportQueryMetric] `json:"metrics,omitempty"`
	MimeType           nullable.Nullable[string]                                         `json:"mimeType,omitempty"`
	ReportDefinitionId nullable.Nullable[string]                                         `json:"reportDefinitionId,omitempty"`
	TimeRange          nullable.Nullable[interface{}]                                    `json:"timeRange,omitempty"`
}
