// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1NatAddress struct {
	IpAddress nullable.Nullable[string]                                 `json:"ipAddress,omitempty"`
	Name      nullable.Nullable[string]                                 `json:"name,omitempty"`
	State     nullable.Nullable[GoogleCloudApigeeV1NatAddressStateEnum] `json:"state,omitempty"`
}
