// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1RatePlanBillingPeriodEnum string

const (
	GoogleCloudApigeeV1RatePlanBillingPeriodEnumBillingPeriodUnspecified GoogleCloudApigeeV1RatePlanBillingPeriodEnum = "BILLING_PERIOD_UNSPECIFIED"
	GoogleCloudApigeeV1RatePlanBillingPeriodEnumMonthly                  GoogleCloudApigeeV1RatePlanBillingPeriodEnum = "MONTHLY"
	GoogleCloudApigeeV1RatePlanBillingPeriodEnumWeekly                   GoogleCloudApigeeV1RatePlanBillingPeriodEnum = "WEEKLY"
)
