// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1RatePlanRevenueShareTypeEnum string

const (
	GoogleCloudApigeeV1RatePlanRevenueShareTypeEnumFixed                       GoogleCloudApigeeV1RatePlanRevenueShareTypeEnum = "FIXED"
	GoogleCloudApigeeV1RatePlanRevenueShareTypeEnumRevenueShareTypeUnspecified GoogleCloudApigeeV1RatePlanRevenueShareTypeEnum = "REVENUE_SHARE_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1RatePlanRevenueShareTypeEnumVolumeBanded                GoogleCloudApigeeV1RatePlanRevenueShareTypeEnum = "VOLUME_BANDED"
)
