// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1InstanceAttachment struct {
	CreatedAt   nullable.Nullable[string] `json:"createdAt,omitempty"`
	Environment nullable.Nullable[string] `json:"environment,omitempty"`
	Name        nullable.Nullable[string] `json:"name,omitempty"`
}
