// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListKeyValueEntriesResponse struct {
	KeyValueEntries nullable.Nullable[[]GoogleCloudApigeeV1KeyValueEntry] `json:"keyValueEntries,omitempty"`
	NextPageToken   nullable.Nullable[string]                             `json:"nextPageToken,omitempty"`
}
