// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListEnvironmentGroupsResponse struct {
	EnvironmentGroups nullable.Nullable[[]GoogleCloudApigeeV1EnvironmentGroup] `json:"environmentGroups,omitempty"`
	NextPageToken     nullable.Nullable[string]                                `json:"nextPageToken,omitempty"`
}
