// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1KeyValueMap struct {
	Encrypted nullable.Nullable[bool]   `json:"encrypted,omitempty"`
	Name      nullable.Nullable[string] `json:"name,omitempty"`
}
