// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListTraceConfigOverridesResponse struct {
	NextPageToken        nullable.Nullable[string]                                   `json:"nextPageToken,omitempty"`
	TraceConfigOverrides nullable.Nullable[[]GoogleCloudApigeeV1TraceConfigOverride] `json:"traceConfigOverrides,omitempty"`
}
