// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityProfileEnvironmentAssociation struct {
	AttachTime                nullable.Nullable[string] `json:"attachTime,omitempty"`
	Name                      nullable.Nullable[string] `json:"name,omitempty"`
	SecurityProfileRevisionId nullable.Nullable[string] `json:"securityProfileRevisionId,omitempty"`
}
