// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ApiCategoryData struct {
	Id         nullable.Nullable[string] `json:"id,omitempty"`
	Name       nullable.Nullable[string] `json:"name,omitempty"`
	SiteId     nullable.Nullable[string] `json:"siteId,omitempty"`
	UpdateTime nullable.Nullable[string] `json:"updateTime,omitempty"`
}
