// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Credential struct {
	ApiProducts    nullable.Nullable[[]GoogleCloudApigeeV1ApiProductRef] `json:"apiProducts,omitempty"`
	Attributes     nullable.Nullable[[]GoogleCloudApigeeV1Attribute]     `json:"attributes,omitempty"`
	ConsumerKey    nullable.Nullable[string]                             `json:"consumerKey,omitempty"`
	ConsumerSecret nullable.Nullable[string]                             `json:"consumerSecret,omitempty"`
	ExpiresAt      nullable.Nullable[string]                             `json:"expiresAt,omitempty"`
	IssuedAt       nullable.Nullable[string]                             `json:"issuedAt,omitempty"`
	Scopes         nullable.Nullable[[]string]                           `json:"scopes,omitempty"`
	Status         nullable.Nullable[string]                             `json:"status,omitempty"`
}
