// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1CustomReport struct {
	ChartType      nullable.Nullable[string]                                  `json:"chartType,omitempty"`
	Comments       nullable.Nullable[[]string]                                `json:"comments,omitempty"`
	CreatedAt      nullable.Nullable[string]                                  `json:"createdAt,omitempty"`
	Dimensions     nullable.Nullable[[]string]                                `json:"dimensions,omitempty"`
	DisplayName    nullable.Nullable[string]                                  `json:"displayName,omitempty"`
	Environment    nullable.Nullable[string]                                  `json:"environment,omitempty"`
	Filter         nullable.Nullable[string]                                  `json:"filter,omitempty"`
	FromTime       nullable.Nullable[string]                                  `json:"fromTime,omitempty"`
	LastModifiedAt nullable.Nullable[string]                                  `json:"lastModifiedAt,omitempty"`
	LastViewedAt   nullable.Nullable[string]                                  `json:"lastViewedAt,omitempty"`
	Limit          nullable.Nullable[string]                                  `json:"limit,omitempty"`
	Metrics        nullable.Nullable[[]GoogleCloudApigeeV1CustomReportMetric] `json:"metrics,omitempty"`
	Name           nullable.Nullable[string]                                  `json:"name,omitempty"`
	Offset         nullable.Nullable[string]                                  `json:"offset,omitempty"`
	Organization   nullable.Nullable[string]                                  `json:"organization,omitempty"`
	Properties     nullable.Nullable[[]GoogleCloudApigeeV1ReportProperty]     `json:"properties,omitempty"`
	SortByCols     nullable.Nullable[[]string]                                `json:"sortByCols,omitempty"`
	SortOrder      nullable.Nullable[string]                                  `json:"sortOrder,omitempty"`
	Tags           nullable.Nullable[[]string]                                `json:"tags,omitempty"`
	TimeUnit       nullable.Nullable[string]                                  `json:"timeUnit,omitempty"`
	ToTime         nullable.Nullable[string]                                  `json:"toTime,omitempty"`
	Topk           nullable.Nullable[string]                                  `json:"topk,omitempty"`
}
