// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListSecurityIncidentsResponse struct {
	NextPageToken     nullable.Nullable[string]                                `json:"nextPageToken,omitempty"`
	SecurityIncidents nullable.Nullable[[]GoogleCloudApigeeV1SecurityIncident] `json:"securityIncidents,omitempty"`
}
