// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1MetricAggregationOrderEnum string

const (
	GoogleCloudApigeeV1MetricAggregationOrderEnumAscending        GoogleCloudApigeeV1MetricAggregationOrderEnum = "ASCENDING"
	GoogleCloudApigeeV1MetricAggregationOrderEnumDescending       GoogleCloudApigeeV1MetricAggregationOrderEnum = "DESCENDING"
	GoogleCloudApigeeV1MetricAggregationOrderEnumOrderUnspecified GoogleCloudApigeeV1MetricAggregationOrderEnum = "ORDER_UNSPECIFIED"
)
