// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Quota struct {
	Interval nullable.Nullable[string] `json:"interval,omitempty"`
	Limit    nullable.Nullable[string] `json:"limit,omitempty"`
	TimeUnit nullable.Nullable[string] `json:"timeUnit,omitempty"`
}
