// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1SecurityReportMetadata struct {
	Dimensions     nullable.Nullable[[]string] `json:"dimensions,omitempty"`
	EndTimestamp   nullable.Nullable[string]   `json:"endTimestamp,omitempty"`
	Metrics        nullable.Nullable[[]string] `json:"metrics,omitempty"`
	MimeType       nullable.Nullable[string]   `json:"mimeType,omitempty"`
	StartTimestamp nullable.Nullable[string]   `json:"startTimestamp,omitempty"`
	TimeUnit       nullable.Nullable[string]   `json:"timeUnit,omitempty"`
}
