// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1QueryTimeSeriesStatsResponseSequence struct {
	Dimensions nullable.Nullable[GoogleCloudApigeeV1QueryTimeSeriesStatsResponseSequenceDimensions] `json:"dimensions,omitempty"`
	Points     nullable.Nullable[[][]interface{}]                                                   `json:"points,omitempty"`
}
