// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1AdjustDeveloperBalanceRequest struct {
	Adjustment nullable.Nullable[GoogleTypeMoney] `json:"adjustment,omitempty"`
}
