// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListDeploymentsResponse struct {
	Deployments nullable.Nullable[[]GoogleCloudApigeeV1Deployment] `json:"deployments,omitempty"`
}
