// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1InstanceDeploymentStatusDeployedRevision struct {
	Percentage nullable.Nullable[int]    `json:"percentage,omitempty"`
	Revision   nullable.Nullable[string] `json:"revision,omitempty"`
}
