// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1QueryMetadata struct {
	Dimensions     nullable.Nullable[[]string] `json:"dimensions,omitempty"`
	EndTimestamp   nullable.Nullable[string]   `json:"endTimestamp,omitempty"`
	Metrics        nullable.Nullable[[]string] `json:"metrics,omitempty"`
	OutputFormat   nullable.Nullable[string]   `json:"outputFormat,omitempty"`
	StartTimestamp nullable.Nullable[string]   `json:"startTimestamp,omitempty"`
	TimeUnit       nullable.Nullable[string]   `json:"timeUnit,omitempty"`
}
