// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1GenerateUploadUrlResponse struct {
	UploadUri nullable.Nullable[string] `json:"uploadUri,omitempty"`
}
