// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ApiCategory struct {
	Data      nullable.Nullable[GoogleCloudApigeeV1ApiCategoryData] `json:"data,omitempty"`
	ErrorCode nullable.Nullable[string]                             `json:"errorCode,omitempty"`
	Message   nullable.Nullable[string]                             `json:"message,omitempty"`
	RequestId nullable.Nullable[string]                             `json:"requestId,omitempty"`
	Status    nullable.Nullable[string]                             `json:"status,omitempty"`
}
