// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1OrganizationStateEnum string

const (
	GoogleCloudApigeeV1OrganizationStateEnumActive           GoogleCloudApigeeV1OrganizationStateEnum = "ACTIVE"
	GoogleCloudApigeeV1OrganizationStateEnumCreating         GoogleCloudApigeeV1OrganizationStateEnum = "CREATING"
	GoogleCloudApigeeV1OrganizationStateEnumDeleting         GoogleCloudApigeeV1OrganizationStateEnum = "DELETING"
	GoogleCloudApigeeV1OrganizationStateEnumStateUnspecified GoogleCloudApigeeV1OrganizationStateEnum = "STATE_UNSPECIFIED"
	GoogleCloudApigeeV1OrganizationStateEnumUpdating         GoogleCloudApigeeV1OrganizationStateEnum = "UPDATING"
)
