// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleTypeMoney struct {
	CurrencyCode nullable.Nullable[string] `json:"currencyCode,omitempty"`
	Nanos        nullable.Nullable[int]    `json:"nanos,omitempty"`
	Units        nullable.Nullable[string] `json:"units,omitempty"`
}
