// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListDebugSessionsResponse struct {
	NextPageToken nullable.Nullable[string]                       `json:"nextPageToken,omitempty"`
	Sessions      nullable.Nullable[[]GoogleCloudApigeeV1Session] `json:"sessions,omitempty"`
}
