// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1DeveloperSubscription struct {
	Apiproduct     nullable.Nullable[string] `json:"apiproduct,omitempty"`
	CreatedAt      nullable.Nullable[string] `json:"createdAt,omitempty"`
	EndTime        nullable.Nullable[string] `json:"endTime,omitempty"`
	LastModifiedAt nullable.Nullable[string] `json:"lastModifiedAt,omitempty"`
	Name           nullable.Nullable[string] `json:"name,omitempty"`
	StartTime      nullable.Nullable[string] `json:"startTime,omitempty"`
}
