// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleApiHttpBody struct {
	ContentType nullable.Nullable[string]                   `json:"contentType,omitempty"`
	Data        nullable.Nullable[string]                   `json:"data,omitempty"`
	Extensions  nullable.Nullable[[]map[string]interface{}] `json:"extensions,omitempty"`
}
