// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ApiProductRef struct {
	Apiproduct nullable.Nullable[string] `json:"apiproduct,omitempty"`
	Status     nullable.Nullable[string] `json:"status,omitempty"`
}
