// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Alias struct {
	Alias     nullable.Nullable[string]                           `json:"alias,omitempty"`
	CertsInfo nullable.Nullable[GoogleCloudApigeeV1Certificate]   `json:"certsInfo,omitempty"`
	Type      nullable.Nullable[GoogleCloudApigeeV1AliasTypeEnum] `json:"type,omitempty"`
}
