// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1OrganizationTypeEnum string

const (
	GoogleCloudApigeeV1OrganizationTypeEnumTypeInternal    GoogleCloudApigeeV1OrganizationTypeEnum = "TYPE_INTERNAL"
	GoogleCloudApigeeV1OrganizationTypeEnumTypePaid        GoogleCloudApigeeV1OrganizationTypeEnum = "TYPE_PAID"
	GoogleCloudApigeeV1OrganizationTypeEnumTypeTrial       GoogleCloudApigeeV1OrganizationTypeEnum = "TYPE_TRIAL"
	GoogleCloudApigeeV1OrganizationTypeEnumTypeUnspecified GoogleCloudApigeeV1OrganizationTypeEnum = "TYPE_UNSPECIFIED"
)
