// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1AliasTypeEnum string

const (
	GoogleCloudApigeeV1AliasTypeEnumAliasTypeUnspecified GoogleCloudApigeeV1AliasTypeEnum = "ALIAS_TYPE_UNSPECIFIED"
	GoogleCloudApigeeV1AliasTypeEnumCert                 GoogleCloudApigeeV1AliasTypeEnum = "CERT"
	GoogleCloudApigeeV1AliasTypeEnumKeyCert              GoogleCloudApigeeV1AliasTypeEnum = "KEY_CERT"
)
