// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ProvisionOrganizationRequest struct {
	AnalyticsRegion   nullable.Nullable[string] `json:"analyticsRegion,omitempty"`
	AuthorizedNetwork nullable.Nullable[string] `json:"authorizedNetwork,omitempty"`
	RuntimeLocation   nullable.Nullable[string] `json:"runtimeLocation,omitempty"`
}
