// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1CustomReportMetric struct {
	Function nullable.Nullable[string] `json:"function,omitempty"`
	Name     nullable.Nullable[string] `json:"name,omitempty"`
}
