// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1MetricAggregationAggregationEnum string

const (
	GoogleCloudApigeeV1MetricAggregationAggregationEnumAggregationFunctionUnspecified GoogleCloudApigeeV1MetricAggregationAggregationEnum = "AGGREGATION_FUNCTION_UNSPECIFIED"
	GoogleCloudApigeeV1MetricAggregationAggregationEnumAvg                            GoogleCloudApigeeV1MetricAggregationAggregationEnum = "AVG"
	GoogleCloudApigeeV1MetricAggregationAggregationEnumCountDistinct                  GoogleCloudApigeeV1MetricAggregationAggregationEnum = "COUNT_DISTINCT"
	GoogleCloudApigeeV1MetricAggregationAggregationEnumMax                            GoogleCloudApigeeV1MetricAggregationAggregationEnum = "MAX"
	GoogleCloudApigeeV1MetricAggregationAggregationEnumMin                            GoogleCloudApigeeV1MetricAggregationAggregationEnum = "MIN"
	GoogleCloudApigeeV1MetricAggregationAggregationEnumSum                            GoogleCloudApigeeV1MetricAggregationAggregationEnum = "SUM"
)
