// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1RatePlanStateEnum string

const (
	GoogleCloudApigeeV1RatePlanStateEnumDraft            GoogleCloudApigeeV1RatePlanStateEnum = "DRAFT"
	GoogleCloudApigeeV1RatePlanStateEnumPublished        GoogleCloudApigeeV1RatePlanStateEnum = "PUBLISHED"
	GoogleCloudApigeeV1RatePlanStateEnumStateUnspecified GoogleCloudApigeeV1RatePlanStateEnum = "STATE_UNSPECIFIED"
)
