// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListOfDevelopersResponse struct {
	Developer nullable.Nullable[[]GoogleCloudApigeeV1Developer] `json:"developer,omitempty"`
}
