// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleRpcPreconditionFailureViolation struct {
	Description nullable.Nullable[string] `json:"description,omitempty"`
	Subject     nullable.Nullable[string] `json:"subject,omitempty"`
	Type        nullable.Nullable[string] `json:"type,omitempty"`
}
