// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1Organization struct {
	AddonsConfig                     nullable.Nullable[GoogleCloudApigeeV1AddonsConfig]                     `json:"addonsConfig,omitempty"`
	AnalyticsRegion                  nullable.Nullable[string]                                              `json:"analyticsRegion,omitempty"`
	ApiConsumerDataEncryptionKeyName nullable.Nullable[string]                                              `json:"apiConsumerDataEncryptionKeyName,omitempty"`
	ApiConsumerDataLocation          nullable.Nullable[string]                                              `json:"apiConsumerDataLocation,omitempty"`
	ApigeeProjectId                  nullable.Nullable[string]                                              `json:"apigeeProjectId,omitempty"`
	Attributes                       nullable.Nullable[[]string]                                            `json:"attributes,omitempty"`
	AuthorizedNetwork                nullable.Nullable[string]                                              `json:"authorizedNetwork,omitempty"`
	BillingType                      nullable.Nullable[GoogleCloudApigeeV1OrganizationBillingTypeEnum]      `json:"billingType,omitempty"`
	CaCertificate                    nullable.Nullable[string]                                              `json:"caCertificate,omitempty"`
	ControlPlaneEncryptionKeyName    nullable.Nullable[string]                                              `json:"controlPlaneEncryptionKeyName,omitempty"`
	CreatedAt                        nullable.Nullable[string]                                              `json:"createdAt,omitempty"`
	CustomerName                     nullable.Nullable[string]                                              `json:"customerName,omitempty"`
	Description                      nullable.Nullable[string]                                              `json:"description,omitempty"`
	DisplayName                      nullable.Nullable[string]                                              `json:"displayName,omitempty"`
	Environments                     nullable.Nullable[[]string]                                            `json:"environments,omitempty"`
	ExpiresAt                        nullable.Nullable[string]                                              `json:"expiresAt,omitempty"`
	LastModifiedAt                   nullable.Nullable[string]                                              `json:"lastModifiedAt,omitempty"`
	Name                             nullable.Nullable[string]                                              `json:"name,omitempty"`
	PortalDisabled                   nullable.Nullable[bool]                                                `json:"portalDisabled,omitempty"`
	ProjectId                        nullable.Nullable[string]                                              `json:"projectId,omitempty"`
	Properties                       nullable.Nullable[GoogleCloudApigeeV1Properties]                       `json:"properties,omitempty"`
	RuntimeDatabaseEncryptionKeyName nullable.Nullable[string]                                              `json:"runtimeDatabaseEncryptionKeyName,omitempty"`
	RuntimeType                      nullable.Nullable[GoogleCloudApigeeV1OrganizationRuntimeTypeEnum]      `json:"runtimeType,omitempty"`
	State                            nullable.Nullable[GoogleCloudApigeeV1OrganizationStateEnum]            `json:"state,omitempty"`
	SubscriptionType                 nullable.Nullable[GoogleCloudApigeeV1OrganizationSubscriptionTypeEnum] `json:"subscriptionType,omitempty"`
	Type                             nullable.Nullable[GoogleCloudApigeeV1OrganizationTypeEnum]             `json:"type,omitempty"`
}
