// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1IntegrationConfig struct {
	Enabled nullable.Nullable[bool] `json:"enabled,omitempty"`
}
