// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleLongrunningListOperationsResponse struct {
	NextPageToken nullable.Nullable[string]                       `json:"nextPageToken,omitempty"`
	Operations    nullable.Nullable[[]GoogleLongrunningOperation] `json:"operations,omitempty"`
}
