// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListApiProxiesResponse struct {
	Proxies nullable.Nullable[[]GoogleCloudApigeeV1ApiProxy] `json:"proxies,omitempty"`
}
