// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1RatePlanPaymentFundingModelEnum string

const (
	GoogleCloudApigeeV1RatePlanPaymentFundingModelEnumPaymentFundingModelUnspecified GoogleCloudApigeeV1RatePlanPaymentFundingModelEnum = "PAYMENT_FUNDING_MODEL_UNSPECIFIED"
	GoogleCloudApigeeV1RatePlanPaymentFundingModelEnumPostpaid                       GoogleCloudApigeeV1RatePlanPaymentFundingModelEnum = "POSTPAID"
	GoogleCloudApigeeV1RatePlanPaymentFundingModelEnumPrepaid                        GoogleCloudApigeeV1RatePlanPaymentFundingModelEnum = "PREPAID"
)
