// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1UpdateErrorCodeEnum string

const (
	GoogleCloudApigeeV1UpdateErrorCodeEnumAborted            GoogleCloudApigeeV1UpdateErrorCodeEnum = "ABORTED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumAlreadyExists      GoogleCloudApigeeV1UpdateErrorCodeEnum = "ALREADY_EXISTS"
	GoogleCloudApigeeV1UpdateErrorCodeEnumCancelled          GoogleCloudApigeeV1UpdateErrorCodeEnum = "CANCELLED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumDataLoss           GoogleCloudApigeeV1UpdateErrorCodeEnum = "DATA_LOSS"
	GoogleCloudApigeeV1UpdateErrorCodeEnumDeadlineExceeded   GoogleCloudApigeeV1UpdateErrorCodeEnum = "DEADLINE_EXCEEDED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumFailedPrecondition GoogleCloudApigeeV1UpdateErrorCodeEnum = "FAILED_PRECONDITION"
	GoogleCloudApigeeV1UpdateErrorCodeEnumInternal           GoogleCloudApigeeV1UpdateErrorCodeEnum = "INTERNAL"
	GoogleCloudApigeeV1UpdateErrorCodeEnumInvalidArgument    GoogleCloudApigeeV1UpdateErrorCodeEnum = "INVALID_ARGUMENT"
	GoogleCloudApigeeV1UpdateErrorCodeEnumNotFound           GoogleCloudApigeeV1UpdateErrorCodeEnum = "NOT_FOUND"
	GoogleCloudApigeeV1UpdateErrorCodeEnumOk                 GoogleCloudApigeeV1UpdateErrorCodeEnum = "OK"
	GoogleCloudApigeeV1UpdateErrorCodeEnumOutOfRange         GoogleCloudApigeeV1UpdateErrorCodeEnum = "OUT_OF_RANGE"
	GoogleCloudApigeeV1UpdateErrorCodeEnumPermissionDenied   GoogleCloudApigeeV1UpdateErrorCodeEnum = "PERMISSION_DENIED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumResourceExhausted  GoogleCloudApigeeV1UpdateErrorCodeEnum = "RESOURCE_EXHAUSTED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumUnauthenticated    GoogleCloudApigeeV1UpdateErrorCodeEnum = "UNAUTHENTICATED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumUnavailable        GoogleCloudApigeeV1UpdateErrorCodeEnum = "UNAVAILABLE"
	GoogleCloudApigeeV1UpdateErrorCodeEnumUnimplemented      GoogleCloudApigeeV1UpdateErrorCodeEnum = "UNIMPLEMENTED"
	GoogleCloudApigeeV1UpdateErrorCodeEnumUnknown            GoogleCloudApigeeV1UpdateErrorCodeEnum = "UNKNOWN"
)
