// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleLongrunningOperation struct {
	Done     nullable.Nullable[bool]                   `json:"done,omitempty"`
	Error    nullable.Nullable[GoogleRpcStatus]        `json:"error,omitempty"`
	Metadata nullable.Nullable[map[string]interface{}] `json:"metadata,omitempty"`
	Name     nullable.Nullable[string]                 `json:"name,omitempty"`
	Response nullable.Nullable[map[string]interface{}] `json:"response,omitempty"`
}
