// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ScoreComponentRecommendationActionActionContext struct {
	DocumentationLink nullable.Nullable[string] `json:"documentationLink,omitempty"`
}
