// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListNatAddressesResponse struct {
	NatAddresses  nullable.Nullable[[]GoogleCloudApigeeV1NatAddress] `json:"natAddresses,omitempty"`
	NextPageToken nullable.Nullable[string]                          `json:"nextPageToken,omitempty"`
}
