// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1TlsInfoCommonName struct {
	Value         nullable.Nullable[string] `json:"value,omitempty"`
	WildcardMatch nullable.Nullable[bool]   `json:"wildcardMatch,omitempty"`
}
