// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListEndpointAttachmentsResponse struct {
	EndpointAttachments nullable.Nullable[[]GoogleCloudApigeeV1EndpointAttachment] `json:"endpointAttachments,omitempty"`
	NextPageToken       nullable.Nullable[string]                                  `json:"nextPageToken,omitempty"`
}
