// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1EntityMetadata struct {
	CreatedAt      nullable.Nullable[string] `json:"createdAt,omitempty"`
	LastModifiedAt nullable.Nullable[string] `json:"lastModifiedAt,omitempty"`
	SubType        nullable.Nullable[string] `json:"subType,omitempty"`
}
