// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1EnvironmentGroupStateEnum string

const (
	GoogleCloudApigeeV1EnvironmentGroupStateEnumActive           GoogleCloudApigeeV1EnvironmentGroupStateEnum = "ACTIVE"
	GoogleCloudApigeeV1EnvironmentGroupStateEnumCreating         GoogleCloudApigeeV1EnvironmentGroupStateEnum = "CREATING"
	GoogleCloudApigeeV1EnvironmentGroupStateEnumDeleting         GoogleCloudApigeeV1EnvironmentGroupStateEnum = "DELETING"
	GoogleCloudApigeeV1EnvironmentGroupStateEnumStateUnspecified GoogleCloudApigeeV1EnvironmentGroupStateEnum = "STATE_UNSPECIFIED"
	GoogleCloudApigeeV1EnvironmentGroupStateEnumUpdating         GoogleCloudApigeeV1EnvironmentGroupStateEnum = "UPDATING"
)
