// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum string

const (
	GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnumDay                   GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum = "DAY"
	GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnumHour                  GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum = "HOUR"
	GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnumMinute                GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum = "MINUTE"
	GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnumMonth                 GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum = "MONTH"
	GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnumWindowSizeUnspecified GoogleCloudApigeeV1QueryTimeSeriesStatsRequestWindowSizeEnum = "WINDOW_SIZE_UNSPECIFIED"
)
