// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListEnvironmentResourcesResponse struct {
	ResourceFile nullable.Nullable[[]GoogleCloudApigeeV1ResourceFile] `json:"resourceFile,omitempty"`
}
