// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1ListSecurityReportsResponse struct {
	NextPageToken   nullable.Nullable[string]                              `json:"nextPageToken,omitempty"`
	SecurityReports nullable.Nullable[[]GoogleCloudApigeeV1SecurityReport] `json:"securityReports,omitempty"`
}
