// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleCloudApigeeV1GenerateDownloadUrlResponse struct {
	DownloadUri nullable.Nullable[string] `json:"downloadUri,omitempty"`
}
