// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum string

const (
	GoogleCloudApigeeV1SecurityIncidentRiskLevelEnumLow                  GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum = "LOW"
	GoogleCloudApigeeV1SecurityIncidentRiskLevelEnumModerate             GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum = "MODERATE"
	GoogleCloudApigeeV1SecurityIncidentRiskLevelEnumRiskLevelUnspecified GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum = "RISK_LEVEL_UNSPECIFIED"
	GoogleCloudApigeeV1SecurityIncidentRiskLevelEnumSevere               GoogleCloudApigeeV1SecurityIncidentRiskLevelEnum = "SEVERE"
)
