// Code generated by Sideko (sideko.dev)
package types

import (
	nullable "apigee_api/nullable"
)

type GoogleTypeInterval struct {
	EndTime   nullable.Nullable[string] `json:"endTime,omitempty"`
	StartTime nullable.Nullable[string] `json:"startTime,omitempty"`
}
