// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1TraceSamplingConfigSamplerEnum string

const (
	GoogleCloudApigeeV1TraceSamplingConfigSamplerEnumOff                GoogleCloudApigeeV1TraceSamplingConfigSamplerEnum = "OFF"
	GoogleCloudApigeeV1TraceSamplingConfigSamplerEnumProbability        GoogleCloudApigeeV1TraceSamplingConfigSamplerEnum = "PROBABILITY"
	GoogleCloudApigeeV1TraceSamplingConfigSamplerEnumSamplerUnspecified GoogleCloudApigeeV1TraceSamplingConfigSamplerEnum = "SAMPLER_UNSPECIFIED"
)
