// Code generated by Sideko (sideko.dev)
package types

type GoogleCloudApigeeV1InstanceStateEnum string

const (
	GoogleCloudApigeeV1InstanceStateEnumActive           GoogleCloudApigeeV1InstanceStateEnum = "ACTIVE"
	GoogleCloudApigeeV1InstanceStateEnumCreating         GoogleCloudApigeeV1InstanceStateEnum = "CREATING"
	GoogleCloudApigeeV1InstanceStateEnumDeleting         GoogleCloudApigeeV1InstanceStateEnum = "DELETING"
	GoogleCloudApigeeV1InstanceStateEnumStateUnspecified GoogleCloudApigeeV1InstanceStateEnum = "STATE_UNSPECIFIED"
	GoogleCloudApigeeV1InstanceStateEnumUpdating         GoogleCloudApigeeV1InstanceStateEnum = "UPDATING"
)
