// Code generated by Sideko (sideko.dev)
package types

type PatchV1NameAltEnum string

const (
	PatchV1NameAltEnumJson  PatchV1NameAltEnum = "json"
	PatchV1NameAltEnumMedia PatchV1NameAltEnum = "media"
	PatchV1NameAltEnumProto PatchV1NameAltEnum = "proto"
)
