// Code generated by Sideko (sideko.dev)
package types

type PatchV1NameXgafvEnum string

const (
	PatchV1NameXgafvEnum1 PatchV1NameXgafvEnum = "1"
	PatchV1NameXgafvEnum2 PatchV1NameXgafvEnum = "2"
)
