// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEntriesXgafvEnum string

const (
	PostV1ParentEntriesXgafvEnum1 PostV1ParentEntriesXgafvEnum = "1"
	PostV1ParentEntriesXgafvEnum2 PostV1ParentEntriesXgafvEnum = "2"
)
