// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSecurityReportsXgafvEnum string

const (
	PostV1ParentSecurityReportsXgafvEnum1 PostV1ParentSecurityReportsXgafvEnum = "1"
	PostV1ParentSecurityReportsXgafvEnum2 PostV1ParentSecurityReportsXgafvEnum = "2"
)
