// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsDatastoresTestXgafvEnum string

const (
	PostV1ParentAnalyticsDatastoresTestXgafvEnum1 PostV1ParentAnalyticsDatastoresTestXgafvEnum = "1"
	PostV1ParentAnalyticsDatastoresTestXgafvEnum2 PostV1ParentAnalyticsDatastoresTestXgafvEnum = "2"
)
