// Code generated by Sideko (sideko.dev)
package types

type PostV1ProjectProvisionOrganizationXgafvEnum string

const (
	PostV1ProjectProvisionOrganizationXgafvEnum1 PostV1ProjectProvisionOrganizationXgafvEnum = "1"
	PostV1ProjectProvisionOrganizationXgafvEnum2 PostV1ProjectProvisionOrganizationXgafvEnum = "2"
)
