// Code generated by Sideko (sideko.dev)
package types

type PostV1ResourceSetIamPolicyXgafvEnum string

const (
	PostV1ResourceSetIamPolicyXgafvEnum1 PostV1ResourceSetIamPolicyXgafvEnum = "1"
	PostV1ResourceSetIamPolicyXgafvEnum2 PostV1ResourceSetIamPolicyXgafvEnum = "2"
)
