// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentResourcefilesXgafvEnum string

const (
	PostV1ParentResourcefilesXgafvEnum1 PostV1ParentResourcefilesXgafvEnum = "1"
	PostV1ParentResourcefilesXgafvEnum2 PostV1ParentResourcefilesXgafvEnum = "2"
)
