// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentReferencesAltEnum string

const (
	PostV1ParentReferencesAltEnumJson  PostV1ParentReferencesAltEnum = "json"
	PostV1ParentReferencesAltEnumMedia PostV1ParentReferencesAltEnum = "media"
	PostV1ParentReferencesAltEnumProto PostV1ParentReferencesAltEnum = "proto"
)
