// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAttachmentsAltEnum string

const (
	PostV1ParentAttachmentsAltEnumJson  PostV1ParentAttachmentsAltEnum = "json"
	PostV1ParentAttachmentsAltEnumMedia PostV1ParentAttachmentsAltEnum = "media"
	PostV1ParentAttachmentsAltEnumProto PostV1ParentAttachmentsAltEnum = "proto"
)
