// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAttributesAltEnum string

const (
	PostV1ParentAttributesAltEnumJson  PostV1ParentAttributesAltEnum = "json"
	PostV1ParentAttributesAltEnumMedia PostV1ParentAttributesAltEnum = "media"
	PostV1ParentAttributesAltEnumProto PostV1ParentAttributesAltEnum = "proto"
)
