// Code generated by Sideko (sideko.dev)
package types

type PostV1NameGetSyncAuthorizationAltEnum string

const (
	PostV1NameGetSyncAuthorizationAltEnumJson  PostV1NameGetSyncAuthorizationAltEnum = "json"
	PostV1NameGetSyncAuthorizationAltEnumMedia PostV1NameGetSyncAuthorizationAltEnum = "media"
	PostV1NameGetSyncAuthorizationAltEnumProto PostV1NameGetSyncAuthorizationAltEnum = "proto"
)
