// Code generated by Sideko (sideko.dev)
package types

type PostV1OrgSetAddonsXgafvEnum string

const (
	PostV1OrgSetAddonsXgafvEnum1 PostV1OrgSetAddonsXgafvEnum = "1"
	PostV1OrgSetAddonsXgafvEnum2 PostV1OrgSetAddonsXgafvEnum = "2"
)
