// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeysAltEnum string

const (
	PostV1ParentKeysAltEnumJson  PostV1ParentKeysAltEnum = "json"
	PostV1ParentKeysAltEnumMedia PostV1ParentKeysAltEnum = "media"
	PostV1ParentKeysAltEnumProto PostV1ParentKeysAltEnum = "proto"
)
