// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeystoresAltEnum string

const (
	PostV1ParentKeystoresAltEnumJson  PostV1ParentKeystoresAltEnum = "json"
	PostV1ParentKeystoresAltEnumMedia PostV1ParentKeystoresAltEnum = "media"
	PostV1ParentKeystoresAltEnumProto PostV1ParentKeystoresAltEnum = "proto"
)
