// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentUnsubscribeXgafvEnum string

const (
	PostV1ParentUnsubscribeXgafvEnum1 PostV1ParentUnsubscribeXgafvEnum = "1"
	PostV1ParentUnsubscribeXgafvEnum2 PostV1ParentUnsubscribeXgafvEnum = "2"
)
