// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApiproductsXgafvEnum string

const (
	PostV1ParentApiproductsXgafvEnum1 PostV1ParentApiproductsXgafvEnum = "1"
	PostV1ParentApiproductsXgafvEnum2 PostV1ParentApiproductsXgafvEnum = "2"
)
