// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentReferencesXgafvEnum string

const (
	PostV1ParentReferencesXgafvEnum1 PostV1ParentReferencesXgafvEnum = "1"
	PostV1ParentReferencesXgafvEnum2 PostV1ParentReferencesXgafvEnum = "2"
)
