// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentArchiveDeploymentsAltEnum string

const (
	PostV1ParentArchiveDeploymentsAltEnumJson  PostV1ParentArchiveDeploymentsAltEnum = "json"
	PostV1ParentArchiveDeploymentsAltEnumMedia PostV1ParentArchiveDeploymentsAltEnum = "media"
	PostV1ParentArchiveDeploymentsAltEnumProto PostV1ParentArchiveDeploymentsAltEnum = "proto"
)
