// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentInstancesXgafvEnum string

const (
	PostV1ParentInstancesXgafvEnum1 PostV1ParentInstancesXgafvEnum = "1"
	PostV1ParentInstancesXgafvEnum2 PostV1ParentInstancesXgafvEnum = "2"
)
