// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAliasesAltEnum string

const (
	PostV1ParentAliasesAltEnumJson  PostV1ParentAliasesAltEnum = "json"
	PostV1ParentAliasesAltEnumMedia PostV1ParentAliasesAltEnum = "media"
	PostV1ParentAliasesAltEnumProto PostV1ParentAliasesAltEnum = "proto"
)
