// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDebugsessionsAltEnum string

const (
	PostV1ParentDebugsessionsAltEnumJson  PostV1ParentDebugsessionsAltEnum = "json"
	PostV1ParentDebugsessionsAltEnumMedia PostV1ParentDebugsessionsAltEnum = "media"
	PostV1ParentDebugsessionsAltEnumProto PostV1ParentDebugsessionsAltEnum = "proto"
)
