// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentHostSecurityReportsXgafvEnum string

const (
	PostV1ParentHostSecurityReportsXgafvEnum1 PostV1ParentHostSecurityReportsXgafvEnum = "1"
	PostV1ParentHostSecurityReportsXgafvEnum2 PostV1ParentHostSecurityReportsXgafvEnum = "2"
)
