// Code generated by Sideko (sideko.dev)
package types

type PostV1ResourceSetIamPolicyAltEnum string

const (
	PostV1ResourceSetIamPolicyAltEnumJson  PostV1ResourceSetIamPolicyAltEnum = "json"
	PostV1ResourceSetIamPolicyAltEnumMedia PostV1ResourceSetIamPolicyAltEnum = "media"
	PostV1ResourceSetIamPolicyAltEnumProto PostV1ResourceSetIamPolicyAltEnum = "proto"
)
