// Code generated by Sideko (sideko.dev)
package types

type PostV1OrgenvSecurityStatsQueryTimeSeriesStatsXgafvEnum string

const (
	PostV1OrgenvSecurityStatsQueryTimeSeriesStatsXgafvEnum1 PostV1OrgenvSecurityStatsQueryTimeSeriesStatsXgafvEnum = "1"
	PostV1OrgenvSecurityStatsQueryTimeSeriesStatsXgafvEnum2 PostV1OrgenvSecurityStatsQueryTimeSeriesStatsXgafvEnum = "2"
)
