// Code generated by Sideko (sideko.dev)
package types

type PostV1NameAdjustXgafvEnum string

const (
	PostV1NameAdjustXgafvEnum1 PostV1NameAdjustXgafvEnum = "1"
	PostV1NameAdjustXgafvEnum2 PostV1NameAdjustXgafvEnum = "2"
)
