// Code generated by Sideko (sideko.dev)
package types

type PostV1OrgenvSecurityStatsQueryTabularStatsAltEnum string

const (
	PostV1OrgenvSecurityStatsQueryTabularStatsAltEnumJson  PostV1OrgenvSecurityStatsQueryTabularStatsAltEnum = "json"
	PostV1OrgenvSecurityStatsQueryTabularStatsAltEnumMedia PostV1OrgenvSecurityStatsQueryTabularStatsAltEnum = "media"
	PostV1OrgenvSecurityStatsQueryTabularStatsAltEnumProto PostV1OrgenvSecurityStatsQueryTabularStatsAltEnum = "proto"
)
