// Code generated by Sideko (sideko.dev)
package types

type PostV1ProfileEnvironmentComputeEnvironmentScoresXgafvEnum string

const (
	PostV1ProfileEnvironmentComputeEnvironmentScoresXgafvEnum1 PostV1ProfileEnvironmentComputeEnvironmentScoresXgafvEnum = "1"
	PostV1ProfileEnvironmentComputeEnvironmentScoresXgafvEnum2 PostV1ProfileEnvironmentComputeEnvironmentScoresXgafvEnum = "2"
)
