// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSharedflowsXgafvEnum string

const (
	PostV1ParentSharedflowsXgafvEnum1 PostV1ParentSharedflowsXgafvEnum = "1"
	PostV1ParentSharedflowsXgafvEnum2 PostV1ParentSharedflowsXgafvEnum = "2"
)
