// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSecurityReportsAltEnum string

const (
	PostV1ParentSecurityReportsAltEnumJson  PostV1ParentSecurityReportsAltEnum = "json"
	PostV1ParentSecurityReportsAltEnumMedia PostV1ParentSecurityReportsAltEnum = "media"
	PostV1ParentSecurityReportsAltEnumProto PostV1ParentSecurityReportsAltEnum = "proto"
)
