// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentUnsubscribeAltEnum string

const (
	PostV1ParentUnsubscribeAltEnumJson  PostV1ParentUnsubscribeAltEnum = "json"
	PostV1ParentUnsubscribeAltEnumMedia PostV1ParentUnsubscribeAltEnum = "media"
	PostV1ParentUnsubscribeAltEnumProto PostV1ParentUnsubscribeAltEnum = "proto"
)
