// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSubscriptionsXgafvEnum string

const (
	PostV1ParentSubscriptionsXgafvEnum1 PostV1ParentSubscriptionsXgafvEnum = "1"
	PostV1ParentSubscriptionsXgafvEnum2 PostV1ParentSubscriptionsXgafvEnum = "2"
)
