// Code generated by Sideko (sideko.dev)
package types

type PostV1NameCreditXgafvEnum string

const (
	PostV1NameCreditXgafvEnum1 PostV1NameCreditXgafvEnum = "1"
	PostV1NameCreditXgafvEnum2 PostV1NameCreditXgafvEnum = "2"
)
