// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEntriesAltEnum string

const (
	PostV1ParentEntriesAltEnumJson  PostV1ParentEntriesAltEnum = "json"
	PostV1ParentEntriesAltEnumMedia PostV1ParentEntriesAltEnum = "media"
	PostV1ParentEntriesAltEnumProto PostV1ParentEntriesAltEnum = "proto"
)
