// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentReportsAltEnum string

const (
	PostV1ParentReportsAltEnumJson  PostV1ParentReportsAltEnum = "json"
	PostV1ParentReportsAltEnumMedia PostV1ParentReportsAltEnum = "media"
	PostV1ParentReportsAltEnumProto PostV1ParentReportsAltEnum = "proto"
)
