// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentReportsXgafvEnum string

const (
	PostV1ParentReportsXgafvEnum1 PostV1ParentReportsXgafvEnum = "1"
	PostV1ParentReportsXgafvEnum2 PostV1ParentReportsXgafvEnum = "2"
)
