// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAliasesXgafvEnum string

const (
	PostV1ParentAliasesXgafvEnum1 PostV1ParentAliasesXgafvEnum = "1"
	PostV1ParentAliasesXgafvEnum2 PostV1ParentAliasesXgafvEnum = "2"
)
