// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDatacollectorsAltEnum string

const (
	PostV1ParentDatacollectorsAltEnumJson  PostV1ParentDatacollectorsAltEnum = "json"
	PostV1ParentDatacollectorsAltEnumMedia PostV1ParentDatacollectorsAltEnum = "media"
	PostV1ParentDatacollectorsAltEnumProto PostV1ParentDatacollectorsAltEnum = "proto"
)
