// Code generated by Sideko (sideko.dev)
package types

type PostV1ProjectProvisionOrganizationAltEnum string

const (
	PostV1ProjectProvisionOrganizationAltEnumJson  PostV1ProjectProvisionOrganizationAltEnum = "json"
	PostV1ProjectProvisionOrganizationAltEnumMedia PostV1ProjectProvisionOrganizationAltEnum = "media"
	PostV1ProjectProvisionOrganizationAltEnumProto PostV1ProjectProvisionOrganizationAltEnum = "proto"
)
