// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDevelopersAltEnum string

const (
	PostV1ParentDevelopersAltEnumJson  PostV1ParentDevelopersAltEnum = "json"
	PostV1ParentDevelopersAltEnumMedia PostV1ParentDevelopersAltEnum = "media"
	PostV1ParentDevelopersAltEnumProto PostV1ParentDevelopersAltEnum = "proto"
)
