// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentRateplansXgafvEnum string

const (
	PostV1ParentRateplansXgafvEnum1 PostV1ParentRateplansXgafvEnum = "1"
	PostV1ParentRateplansXgafvEnum2 PostV1ParentRateplansXgafvEnum = "2"
)
