// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSubscribeXgafvEnum string

const (
	PostV1ParentSubscribeXgafvEnum1 PostV1ParentSubscribeXgafvEnum = "1"
	PostV1ParentSubscribeXgafvEnum2 PostV1ParentSubscribeXgafvEnum = "2"
)
