// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDatacollectorsXgafvEnum string

const (
	PostV1ParentDatacollectorsXgafvEnum1 PostV1ParentDatacollectorsXgafvEnum = "1"
	PostV1ParentDatacollectorsXgafvEnum2 PostV1ParentDatacollectorsXgafvEnum = "2"
)
