// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsExportsXgafvEnum string

const (
	PostV1ParentAnalyticsExportsXgafvEnum1 PostV1ParentAnalyticsExportsXgafvEnum = "1"
	PostV1ParentAnalyticsExportsXgafvEnum2 PostV1ParentAnalyticsExportsXgafvEnum = "2"
)
