// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApisXgafvEnum string

const (
	PostV1ParentApisXgafvEnum1 PostV1ParentApisXgafvEnum = "1"
	PostV1ParentApisXgafvEnum2 PostV1ParentApisXgafvEnum = "2"
)
