// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDevelopersXgafvEnum string

const (
	PostV1ParentDevelopersXgafvEnum1 PostV1ParentDevelopersXgafvEnum = "1"
	PostV1ParentDevelopersXgafvEnum2 PostV1ParentDevelopersXgafvEnum = "2"
)
