// Code generated by Sideko (sideko.dev)
package types

type PostV1NameSetSyncAuthorizationAltEnum string

const (
	PostV1NameSetSyncAuthorizationAltEnumJson  PostV1NameSetSyncAuthorizationAltEnum = "json"
	PostV1NameSetSyncAuthorizationAltEnumMedia PostV1NameSetSyncAuthorizationAltEnum = "media"
	PostV1NameSetSyncAuthorizationAltEnumProto PostV1NameSetSyncAuthorizationAltEnum = "proto"
)
