// Code generated by Sideko (sideko.dev)
package types

type PostV1NameGenerateDownloadUrlAltEnum string

const (
	PostV1NameGenerateDownloadUrlAltEnumJson  PostV1NameGenerateDownloadUrlAltEnum = "json"
	PostV1NameGenerateDownloadUrlAltEnumMedia PostV1NameGenerateDownloadUrlAltEnum = "media"
	PostV1NameGenerateDownloadUrlAltEnumProto PostV1NameGenerateDownloadUrlAltEnum = "proto"
)
