// Code generated by Sideko (sideko.dev)
package types

type PostV1NameAltEnum string

const (
	PostV1NameAltEnumJson  PostV1NameAltEnum = "json"
	PostV1NameAltEnumMedia PostV1NameAltEnum = "media"
	PostV1NameAltEnumProto PostV1NameAltEnum = "proto"
)
