// Code generated by Sideko (sideko.dev)
package types

type PostV1ResourceTestIamPermissionsAltEnum string

const (
	PostV1ResourceTestIamPermissionsAltEnumJson  PostV1ResourceTestIamPermissionsAltEnum = "json"
	PostV1ResourceTestIamPermissionsAltEnumMedia PostV1ResourceTestIamPermissionsAltEnum = "media"
	PostV1ResourceTestIamPermissionsAltEnumProto PostV1ResourceTestIamPermissionsAltEnum = "proto"
)
