// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeysXgafvEnum string

const (
	PostV1ParentKeysXgafvEnum1 PostV1ParentKeysXgafvEnum = "1"
	PostV1ParentKeysXgafvEnum2 PostV1ParentKeysXgafvEnum = "2"
)
