// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAppsAltEnum string

const (
	PostV1ParentAppsAltEnumJson  PostV1ParentAppsAltEnum = "json"
	PostV1ParentAppsAltEnumMedia PostV1ParentAppsAltEnum = "media"
	PostV1ParentAppsAltEnumProto PostV1ParentAppsAltEnum = "proto"
)
