// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsDatastoresXgafvEnum string

const (
	PostV1ParentAnalyticsDatastoresXgafvEnum1 PostV1ParentAnalyticsDatastoresXgafvEnum = "1"
	PostV1ParentAnalyticsDatastoresXgafvEnum2 PostV1ParentAnalyticsDatastoresXgafvEnum = "2"
)
