// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentResourcefilesAltEnum string

const (
	PostV1ParentResourcefilesAltEnumJson  PostV1ParentResourcefilesAltEnum = "json"
	PostV1ParentResourcefilesAltEnumMedia PostV1ParentResourcefilesAltEnum = "media"
	PostV1ParentResourcefilesAltEnumProto PostV1ParentResourcefilesAltEnum = "proto"
)
