// Code generated by Sideko (sideko.dev)
package types

type PostV1NameActivateXgafvEnum string

const (
	PostV1NameActivateXgafvEnum1 PostV1NameActivateXgafvEnum = "1"
	PostV1NameActivateXgafvEnum2 PostV1NameActivateXgafvEnum = "2"
)
