// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEnvgroupsAltEnum string

const (
	PostV1ParentEnvgroupsAltEnumJson  PostV1ParentEnvgroupsAltEnum = "json"
	PostV1ParentEnvgroupsAltEnumMedia PostV1ParentEnvgroupsAltEnum = "media"
	PostV1ParentEnvgroupsAltEnumProto PostV1ParentEnvgroupsAltEnum = "proto"
)
