// Code generated by Sideko (sideko.dev)
package types

type PostV1NameAdjustAltEnum string

const (
	PostV1NameAdjustAltEnumJson  PostV1NameAdjustAltEnum = "json"
	PostV1NameAdjustAltEnumMedia PostV1NameAdjustAltEnum = "media"
	PostV1NameAdjustAltEnumProto PostV1NameAdjustAltEnum = "proto"
)
