// Code generated by Sideko (sideko.dev)
package types

type PostV1NameAttributesAltEnum string

const (
	PostV1NameAttributesAltEnumJson  PostV1NameAttributesAltEnum = "json"
	PostV1NameAttributesAltEnumMedia PostV1NameAttributesAltEnum = "media"
	PostV1NameAttributesAltEnumProto PostV1NameAttributesAltEnum = "proto"
)
