// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentCanaryevaluationsAltEnum string

const (
	PostV1ParentCanaryevaluationsAltEnumJson  PostV1ParentCanaryevaluationsAltEnum = "json"
	PostV1ParentCanaryevaluationsAltEnumMedia PostV1ParentCanaryevaluationsAltEnum = "media"
	PostV1ParentCanaryevaluationsAltEnumProto PostV1ParentCanaryevaluationsAltEnum = "proto"
)
