// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentNatAddressesAltEnum string

const (
	PostV1ParentNatAddressesAltEnumJson  PostV1ParentNatAddressesAltEnum = "json"
	PostV1ParentNatAddressesAltEnumMedia PostV1ParentNatAddressesAltEnum = "media"
	PostV1ParentNatAddressesAltEnumProto PostV1ParentNatAddressesAltEnum = "proto"
)
