// Code generated by Sideko (sideko.dev)
package types

type PostV1NameGetSyncAuthorizationXgafvEnum string

const (
	PostV1NameGetSyncAuthorizationXgafvEnum1 PostV1NameGetSyncAuthorizationXgafvEnum = "1"
	PostV1NameGetSyncAuthorizationXgafvEnum2 PostV1NameGetSyncAuthorizationXgafvEnum = "2"
)
