// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSharedflowsAltEnum string

const (
	PostV1ParentSharedflowsAltEnumJson  PostV1ParentSharedflowsAltEnum = "json"
	PostV1ParentSharedflowsAltEnumMedia PostV1ParentSharedflowsAltEnum = "media"
	PostV1ParentSharedflowsAltEnumProto PostV1ParentSharedflowsAltEnum = "proto"
)
