// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeystoresXgafvEnum string

const (
	PostV1ParentKeystoresXgafvEnum1 PostV1ParentKeystoresXgafvEnum = "1"
	PostV1ParentKeystoresXgafvEnum2 PostV1ParentKeystoresXgafvEnum = "2"
)
