// Code generated by Sideko (sideko.dev)
package types

type PostV1NameCreditAltEnum string

const (
	PostV1NameCreditAltEnumJson  PostV1NameCreditAltEnum = "json"
	PostV1NameCreditAltEnumMedia PostV1NameCreditAltEnum = "media"
	PostV1NameCreditAltEnumProto PostV1NameCreditAltEnum = "proto"
)
