// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSubscribeAltEnum string

const (
	PostV1ParentSubscribeAltEnumJson  PostV1ParentSubscribeAltEnum = "json"
	PostV1ParentSubscribeAltEnumMedia PostV1ParentSubscribeAltEnum = "media"
	PostV1ParentSubscribeAltEnumProto PostV1ParentSubscribeAltEnum = "proto"
)
