// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentTargetserversXgafvEnum string

const (
	PostV1ParentTargetserversXgafvEnum1 PostV1ParentTargetserversXgafvEnum = "1"
	PostV1ParentTargetserversXgafvEnum2 PostV1ParentTargetserversXgafvEnum = "2"
)
