// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentOverridesAltEnum string

const (
	PostV1ParentOverridesAltEnumJson  PostV1ParentOverridesAltEnum = "json"
	PostV1ParentOverridesAltEnumMedia PostV1ParentOverridesAltEnum = "media"
	PostV1ParentOverridesAltEnumProto PostV1ParentOverridesAltEnum = "proto"
)
