// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentHostQueriesXgafvEnum string

const (
	PostV1ParentHostQueriesXgafvEnum1 PostV1ParentHostQueriesXgafvEnum = "1"
	PostV1ParentHostQueriesXgafvEnum2 PostV1ParentHostQueriesXgafvEnum = "2"
)
