// Code generated by Sideko (sideko.dev)
package types

type PostV1NameActivateAltEnum string

const (
	PostV1NameActivateAltEnumJson  PostV1NameActivateAltEnum = "json"
	PostV1NameActivateAltEnumMedia PostV1NameActivateAltEnum = "media"
	PostV1NameActivateAltEnumProto PostV1NameActivateAltEnum = "proto"
)
