// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentArchiveDeploymentsGenerateUploadUrlXgafvEnum string

const (
	PostV1ParentArchiveDeploymentsGenerateUploadUrlXgafvEnum1 PostV1ParentArchiveDeploymentsGenerateUploadUrlXgafvEnum = "1"
	PostV1ParentArchiveDeploymentsGenerateUploadUrlXgafvEnum2 PostV1ParentArchiveDeploymentsGenerateUploadUrlXgafvEnum = "2"
)
