// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentQueriesXgafvEnum string

const (
	PostV1ParentQueriesXgafvEnum1 PostV1ParentQueriesXgafvEnum = "1"
	PostV1ParentQueriesXgafvEnum2 PostV1ParentQueriesXgafvEnum = "2"
)
