// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeyvaluemapsAltEnum string

const (
	PostV1ParentKeyvaluemapsAltEnumJson  PostV1ParentKeyvaluemapsAltEnum = "json"
	PostV1ParentKeyvaluemapsAltEnumMedia PostV1ParentKeyvaluemapsAltEnum = "media"
	PostV1ParentKeyvaluemapsAltEnumProto PostV1ParentKeyvaluemapsAltEnum = "proto"
)
