// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEndpointAttachmentsAltEnum string

const (
	PostV1ParentEndpointAttachmentsAltEnumJson  PostV1ParentEndpointAttachmentsAltEnum = "json"
	PostV1ParentEndpointAttachmentsAltEnumMedia PostV1ParentEndpointAttachmentsAltEnum = "media"
	PostV1ParentEndpointAttachmentsAltEnumProto PostV1ParentEndpointAttachmentsAltEnum = "proto"
)
