// Code generated by Sideko (sideko.dev)
package types

type PostV1NameSetSyncAuthorizationXgafvEnum string

const (
	PostV1NameSetSyncAuthorizationXgafvEnum1 PostV1NameSetSyncAuthorizationXgafvEnum = "1"
	PostV1NameSetSyncAuthorizationXgafvEnum2 PostV1NameSetSyncAuthorizationXgafvEnum = "2"
)
