// Code generated by Sideko (sideko.dev)
package types

type PostV1NameAttributesXgafvEnum string

const (
	PostV1NameAttributesXgafvEnum1 PostV1NameAttributesXgafvEnum = "1"
	PostV1NameAttributesXgafvEnum2 PostV1NameAttributesXgafvEnum = "2"
)
