// Code generated by Sideko (sideko.dev)
package types

type PostV1OrganizationsXgafvEnum string

const (
	PostV1OrganizationsXgafvEnum1 PostV1OrganizationsXgafvEnum = "1"
	PostV1OrganizationsXgafvEnum2 PostV1OrganizationsXgafvEnum = "2"
)
