// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentTargetserversAltEnum string

const (
	PostV1ParentTargetserversAltEnumJson  PostV1ParentTargetserversAltEnum = "json"
	PostV1ParentTargetserversAltEnumMedia PostV1ParentTargetserversAltEnum = "media"
	PostV1ParentTargetserversAltEnumProto PostV1ParentTargetserversAltEnum = "proto"
)
