// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsExportsAltEnum string

const (
	PostV1ParentAnalyticsExportsAltEnumJson  PostV1ParentAnalyticsExportsAltEnum = "json"
	PostV1ParentAnalyticsExportsAltEnumMedia PostV1ParentAnalyticsExportsAltEnum = "media"
	PostV1ParentAnalyticsExportsAltEnumProto PostV1ParentAnalyticsExportsAltEnum = "proto"
)
