// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentSubscriptionsAltEnum string

const (
	PostV1ParentSubscriptionsAltEnumJson  PostV1ParentSubscriptionsAltEnum = "json"
	PostV1ParentSubscriptionsAltEnumMedia PostV1ParentSubscriptionsAltEnum = "media"
	PostV1ParentSubscriptionsAltEnumProto PostV1ParentSubscriptionsAltEnum = "proto"
)
