// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAttachmentsXgafvEnum string

const (
	PostV1ParentAttachmentsXgafvEnum1 PostV1ParentAttachmentsXgafvEnum = "1"
	PostV1ParentAttachmentsXgafvEnum2 PostV1ParentAttachmentsXgafvEnum = "2"
)
