// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentOverridesXgafvEnum string

const (
	PostV1ParentOverridesXgafvEnum1 PostV1ParentOverridesXgafvEnum = "1"
	PostV1ParentOverridesXgafvEnum2 PostV1ParentOverridesXgafvEnum = "2"
)
