// Code generated by Sideko (sideko.dev)
package types

type PostV1ResourceTestIamPermissionsXgafvEnum string

const (
	PostV1ResourceTestIamPermissionsXgafvEnum1 PostV1ResourceTestIamPermissionsXgafvEnum = "1"
	PostV1ResourceTestIamPermissionsXgafvEnum2 PostV1ResourceTestIamPermissionsXgafvEnum = "2"
)
