// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAttributesXgafvEnum string

const (
	PostV1ParentAttributesXgafvEnum1 PostV1ParentAttributesXgafvEnum = "1"
	PostV1ParentAttributesXgafvEnum2 PostV1ParentAttributesXgafvEnum = "2"
)
