// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentHostSecurityReportsAltEnum string

const (
	PostV1ParentHostSecurityReportsAltEnumJson  PostV1ParentHostSecurityReportsAltEnum = "json"
	PostV1ParentHostSecurityReportsAltEnumMedia PostV1ParentHostSecurityReportsAltEnum = "media"
	PostV1ParentHostSecurityReportsAltEnumProto PostV1ParentHostSecurityReportsAltEnum = "proto"
)
