// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeysCreateXgafvEnum string

const (
	PostV1ParentKeysCreateXgafvEnum1 PostV1ParentKeysCreateXgafvEnum = "1"
	PostV1ParentKeysCreateXgafvEnum2 PostV1ParentKeysCreateXgafvEnum = "2"
)
