// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApisAltEnum string

const (
	PostV1ParentApisAltEnumJson  PostV1ParentApisAltEnum = "json"
	PostV1ParentApisAltEnumMedia PostV1ParentApisAltEnum = "media"
	PostV1ParentApisAltEnumProto PostV1ParentApisAltEnum = "proto"
)
