// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentArchiveDeploymentsXgafvEnum string

const (
	PostV1ParentArchiveDeploymentsXgafvEnum1 PostV1ParentArchiveDeploymentsXgafvEnum = "1"
	PostV1ParentArchiveDeploymentsXgafvEnum2 PostV1ParentArchiveDeploymentsXgafvEnum = "2"
)
