// Code generated by Sideko (sideko.dev)
package types

type PostV1OrganizationsAltEnum string

const (
	PostV1OrganizationsAltEnumJson  PostV1OrganizationsAltEnum = "json"
	PostV1OrganizationsAltEnumMedia PostV1OrganizationsAltEnum = "media"
	PostV1OrganizationsAltEnumProto PostV1OrganizationsAltEnum = "proto"
)
