// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentHostQueriesAltEnum string

const (
	PostV1ParentHostQueriesAltEnumJson  PostV1ParentHostQueriesAltEnum = "json"
	PostV1ParentHostQueriesAltEnumMedia PostV1ParentHostQueriesAltEnum = "media"
	PostV1ParentHostQueriesAltEnumProto PostV1ParentHostQueriesAltEnum = "proto"
)
