// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEnvironmentsXgafvEnum string

const (
	PostV1ParentEnvironmentsXgafvEnum1 PostV1ParentEnvironmentsXgafvEnum = "1"
	PostV1ParentEnvironmentsXgafvEnum2 PostV1ParentEnvironmentsXgafvEnum = "2"
)
