// Code generated by Sideko (sideko.dev)
package types

type PostV1InstanceReportStatusAltEnum string

const (
	PostV1InstanceReportStatusAltEnumJson  PostV1InstanceReportStatusAltEnum = "json"
	PostV1InstanceReportStatusAltEnumMedia PostV1InstanceReportStatusAltEnum = "media"
	PostV1InstanceReportStatusAltEnumProto PostV1InstanceReportStatusAltEnum = "proto"
)
