// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsDatastoresAltEnum string

const (
	PostV1ParentAnalyticsDatastoresAltEnumJson  PostV1ParentAnalyticsDatastoresAltEnum = "json"
	PostV1ParentAnalyticsDatastoresAltEnumMedia PostV1ParentAnalyticsDatastoresAltEnum = "media"
	PostV1ParentAnalyticsDatastoresAltEnumProto PostV1ParentAnalyticsDatastoresAltEnum = "proto"
)
