// Code generated by Sideko (sideko.dev)
package types

type PostV1NameGenerateDownloadUrlXgafvEnum string

const (
	PostV1NameGenerateDownloadUrlXgafvEnum1 PostV1NameGenerateDownloadUrlXgafvEnum = "1"
	PostV1NameGenerateDownloadUrlXgafvEnum2 PostV1NameGenerateDownloadUrlXgafvEnum = "2"
)
