// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEnvironmentsAltEnum string

const (
	PostV1ParentEnvironmentsAltEnumJson  PostV1ParentEnvironmentsAltEnum = "json"
	PostV1ParentEnvironmentsAltEnumMedia PostV1ParentEnvironmentsAltEnum = "media"
	PostV1ParentEnvironmentsAltEnumProto PostV1ParentEnvironmentsAltEnum = "proto"
)
