// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentDebugsessionsXgafvEnum string

const (
	PostV1ParentDebugsessionsXgafvEnum1 PostV1ParentDebugsessionsXgafvEnum = "1"
	PostV1ParentDebugsessionsXgafvEnum2 PostV1ParentDebugsessionsXgafvEnum = "2"
)
