// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEndpointAttachmentsXgafvEnum string

const (
	PostV1ParentEndpointAttachmentsXgafvEnum1 PostV1ParentEndpointAttachmentsXgafvEnum = "1"
	PostV1ParentEndpointAttachmentsXgafvEnum2 PostV1ParentEndpointAttachmentsXgafvEnum = "2"
)
