// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApiproductsAltEnum string

const (
	PostV1ParentApiproductsAltEnumJson  PostV1ParentApiproductsAltEnum = "json"
	PostV1ParentApiproductsAltEnumMedia PostV1ParentApiproductsAltEnum = "media"
	PostV1ParentApiproductsAltEnumProto PostV1ParentApiproductsAltEnum = "proto"
)
