// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAnalyticsDatastoresTestAltEnum string

const (
	PostV1ParentAnalyticsDatastoresTestAltEnumJson  PostV1ParentAnalyticsDatastoresTestAltEnum = "json"
	PostV1ParentAnalyticsDatastoresTestAltEnumMedia PostV1ParentAnalyticsDatastoresTestAltEnum = "media"
	PostV1ParentAnalyticsDatastoresTestAltEnumProto PostV1ParentAnalyticsDatastoresTestAltEnum = "proto"
)
