// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentAppsXgafvEnum string

const (
	PostV1ParentAppsXgafvEnum1 PostV1ParentAppsXgafvEnum = "1"
	PostV1ParentAppsXgafvEnum2 PostV1ParentAppsXgafvEnum = "2"
)
