// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApicategoriesAltEnum string

const (
	PostV1ParentApicategoriesAltEnumJson  PostV1ParentApicategoriesAltEnum = "json"
	PostV1ParentApicategoriesAltEnumMedia PostV1ParentApicategoriesAltEnum = "media"
	PostV1ParentApicategoriesAltEnumProto PostV1ParentApicategoriesAltEnum = "proto"
)
