// Code generated by Sideko (sideko.dev)
package types

type PostV1NameDeploymentsAltEnum string

const (
	PostV1NameDeploymentsAltEnumJson  PostV1NameDeploymentsAltEnum = "json"
	PostV1NameDeploymentsAltEnumMedia PostV1NameDeploymentsAltEnum = "media"
	PostV1NameDeploymentsAltEnumProto PostV1NameDeploymentsAltEnum = "proto"
)
