// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentInstancesAltEnum string

const (
	PostV1ParentInstancesAltEnumJson  PostV1ParentInstancesAltEnum = "json"
	PostV1ParentInstancesAltEnumMedia PostV1ParentInstancesAltEnum = "media"
	PostV1ParentInstancesAltEnumProto PostV1ParentInstancesAltEnum = "proto"
)
