// Code generated by Sideko (sideko.dev)
package types

type PostV1NameDeploymentsXgafvEnum string

const (
	PostV1NameDeploymentsXgafvEnum1 PostV1NameDeploymentsXgafvEnum = "1"
	PostV1NameDeploymentsXgafvEnum2 PostV1NameDeploymentsXgafvEnum = "2"
)
