// Code generated by Sideko (sideko.dev)
package types

type PostV1InstanceReportStatusXgafvEnum string

const (
	PostV1InstanceReportStatusXgafvEnum1 PostV1InstanceReportStatusXgafvEnum = "1"
	PostV1InstanceReportStatusXgafvEnum2 PostV1InstanceReportStatusXgafvEnum = "2"
)
