// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentEnvgroupsXgafvEnum string

const (
	PostV1ParentEnvgroupsXgafvEnum1 PostV1ParentEnvgroupsXgafvEnum = "1"
	PostV1ParentEnvgroupsXgafvEnum2 PostV1ParentEnvgroupsXgafvEnum = "2"
)
