// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentRateplansAltEnum string

const (
	PostV1ParentRateplansAltEnumJson  PostV1ParentRateplansAltEnum = "json"
	PostV1ParentRateplansAltEnumMedia PostV1ParentRateplansAltEnum = "media"
	PostV1ParentRateplansAltEnumProto PostV1ParentRateplansAltEnum = "proto"
)
