// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeyvaluemapsXgafvEnum string

const (
	PostV1ParentKeyvaluemapsXgafvEnum1 PostV1ParentKeyvaluemapsXgafvEnum = "1"
	PostV1ParentKeyvaluemapsXgafvEnum2 PostV1ParentKeyvaluemapsXgafvEnum = "2"
)
