// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentCanaryevaluationsXgafvEnum string

const (
	PostV1ParentCanaryevaluationsXgafvEnum1 PostV1ParentCanaryevaluationsXgafvEnum = "1"
	PostV1ParentCanaryevaluationsXgafvEnum2 PostV1ParentCanaryevaluationsXgafvEnum = "2"
)
