// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentKeysCreateAltEnum string

const (
	PostV1ParentKeysCreateAltEnumJson  PostV1ParentKeysCreateAltEnum = "json"
	PostV1ParentKeysCreateAltEnumMedia PostV1ParentKeysCreateAltEnum = "media"
	PostV1ParentKeysCreateAltEnumProto PostV1ParentKeysCreateAltEnum = "proto"
)
