// Code generated by Sideko (sideko.dev)
package types

type PostV1NameExpireAltEnum string

const (
	PostV1NameExpireAltEnumJson  PostV1NameExpireAltEnum = "json"
	PostV1NameExpireAltEnumMedia PostV1NameExpireAltEnum = "media"
	PostV1NameExpireAltEnumProto PostV1NameExpireAltEnum = "proto"
)
