// Code generated by Sideko (sideko.dev)
package types

type PostV1NameExpireXgafvEnum string

const (
	PostV1NameExpireXgafvEnum1 PostV1NameExpireXgafvEnum = "1"
	PostV1NameExpireXgafvEnum2 PostV1NameExpireXgafvEnum = "2"
)
