// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentNatAddressesXgafvEnum string

const (
	PostV1ParentNatAddressesXgafvEnum1 PostV1ParentNatAddressesXgafvEnum = "1"
	PostV1ParentNatAddressesXgafvEnum2 PostV1ParentNatAddressesXgafvEnum = "2"
)
