// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentQueriesAltEnum string

const (
	PostV1ParentQueriesAltEnumJson  PostV1ParentQueriesAltEnum = "json"
	PostV1ParentQueriesAltEnumMedia PostV1ParentQueriesAltEnum = "media"
	PostV1ParentQueriesAltEnumProto PostV1ParentQueriesAltEnum = "proto"
)
