// Code generated by Sideko (sideko.dev)
package types

type PostV1ParentApicategoriesXgafvEnum string

const (
	PostV1ParentApicategoriesXgafvEnum1 PostV1ParentApicategoriesXgafvEnum = "1"
	PostV1ParentApicategoriesXgafvEnum2 PostV1ParentApicategoriesXgafvEnum = "2"
)
