// Code generated by Sideko (sideko.dev)
package types

type PostV1OrgenvSecurityStatsQueryTabularStatsXgafvEnum string

const (
	PostV1OrgenvSecurityStatsQueryTabularStatsXgafvEnum1 PostV1OrgenvSecurityStatsQueryTabularStatsXgafvEnum = "1"
	PostV1OrgenvSecurityStatsQueryTabularStatsXgafvEnum2 PostV1OrgenvSecurityStatsQueryTabularStatsXgafvEnum = "2"
)
