// Code generated by Sideko (sideko.dev)
package types

type PutV1NameAltEnum string

const (
	PutV1NameAltEnumJson  PutV1NameAltEnum = "json"
	PutV1NameAltEnumMedia PutV1NameAltEnum = "media"
	PutV1NameAltEnumProto PutV1NameAltEnum = "proto"
)
