// Code generated by Sideko (sideko.dev)
package types

type PutV1ParentResourcefilesTypeNameAltEnum string

const (
	PutV1ParentResourcefilesTypeNameAltEnumJson  PutV1ParentResourcefilesTypeNameAltEnum = "json"
	PutV1ParentResourcefilesTypeNameAltEnumMedia PutV1ParentResourcefilesTypeNameAltEnum = "media"
	PutV1ParentResourcefilesTypeNameAltEnumProto PutV1ParentResourcefilesTypeNameAltEnum = "proto"
)
