// Code generated by Sideko (sideko.dev)
package types

type PutV1ParentResourcefilesTypeNameXgafvEnum string

const (
	PutV1ParentResourcefilesTypeNameXgafvEnum1 PutV1ParentResourcefilesTypeNameXgafvEnum = "1"
	PutV1ParentResourcefilesTypeNameXgafvEnum2 PutV1ParentResourcefilesTypeNameXgafvEnum = "2"
)
