// Code generated by Sideko (sideko.dev)
package data

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type DeleteRequest struct {
	Name           string                                             `json:"name"`
	QueryXgafv     nullable.Nullable[types.DeleteV1NameDataXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                          `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.DeleteV1NameDataAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                          `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                          `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                          `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                          `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                            `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                          `json:"quotaUser,omitempty"`
	UploadType     nullable.Nullable[string]                          `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                          `json:"uploadProtocol,omitempty"`
}
