// Code generated by Sideko (sideko.dev)
package resourcefiles

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type ListRequest struct {
	Parent         string                                                     `json:"parent"`
	QueryXgafv     nullable.Nullable[types.GetV1ParentResourcefilesXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                                  `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.GetV1ParentResourcefilesAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                                  `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                                  `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                                  `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                                  `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                                    `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                                  `json:"quotaUser,omitempty"`
	Type           nullable.Nullable[string]                                  `json:"type,omitempty"`
	UploadType     nullable.Nullable[string]                                  `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                                  `json:"uploadProtocol,omitempty"`
}

type GetRequest struct {
	Parent         string                                                         `json:"parent"`
	Type           string                                                         `json:"type"`
	QueryXgafv     nullable.Nullable[types.GetV1ParentResourcefilesTypeXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                                      `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.GetV1ParentResourcefilesTypeAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                                      `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                                      `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                                      `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                                      `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                                        `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                                      `json:"quotaUser,omitempty"`
	UploadType     nullable.Nullable[string]                                      `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                                      `json:"uploadProtocol,omitempty"`
}

type CreateRequest struct {
	Parent         string                                                      `json:"parent"`
	QueryXgafv     nullable.Nullable[types.PostV1ParentResourcefilesXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                                   `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.PostV1ParentResourcefilesAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                                   `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                                   `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                                   `json:"key,omitempty"`
	Name           nullable.Nullable[string]                                   `json:"name,omitempty"`
	OauthToken     nullable.Nullable[string]                                   `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                                     `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                                   `json:"quotaUser,omitempty"`
	Type           nullable.Nullable[string]                                   `json:"type,omitempty"`
	UploadType     nullable.Nullable[string]                                   `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                                   `json:"uploadProtocol,omitempty"`
	Data           types.GoogleApiHttpBody                                     `json:"data"`
}
