// Code generated by Sideko (sideko.dev)
package deployments

import (
	nullable "apigee_api/nullable"
	types "apigee_api/types"
)

type DeleteRequest struct {
	Name             string                                                    `json:"name"`
	QueryXgafv       nullable.Nullable[types.DeleteV1NameDeploymentsXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken      nullable.Nullable[string]                                 `json:"accessToken,omitempty"`
	Alt              nullable.Nullable[types.DeleteV1NameDeploymentsAltEnum]   `json:"alt,omitempty"`
	Callback         nullable.Nullable[string]                                 `json:"callback,omitempty"`
	Fields           nullable.Nullable[string]                                 `json:"fields,omitempty"`
	Key              nullable.Nullable[string]                                 `json:"key,omitempty"`
	OauthToken       nullable.Nullable[string]                                 `json:"oauthToken,omitempty"`
	PrettyPrint      nullable.Nullable[bool]                                   `json:"prettyPrint,omitempty"`
	QuotaUser        nullable.Nullable[string]                                 `json:"quotaUser,omitempty"`
	SequencedRollout nullable.Nullable[bool]                                   `json:"sequencedRollout,omitempty"`
	UploadType       nullable.Nullable[string]                                 `json:"uploadType,omitempty"`
	UploadProtocol   nullable.Nullable[string]                                 `json:"uploadProtocol,omitempty"`
}

type ListRequest struct {
	Name           string                                                 `json:"name"`
	QueryXgafv     nullable.Nullable[types.GetV1NameDeploymentsXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                              `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.GetV1NameDeploymentsAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                              `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                              `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                              `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                              `json:"oauthToken,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                                `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                              `json:"quotaUser,omitempty"`
	UploadType     nullable.Nullable[string]                              `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                              `json:"uploadProtocol,omitempty"`
}

type CreateRequest struct {
	Name           string                                                  `json:"name"`
	QueryXgafv     nullable.Nullable[types.PostV1NameDeploymentsXgafvEnum] `json:"queryXgafv,omitempty"`
	AccessToken    nullable.Nullable[string]                               `json:"accessToken,omitempty"`
	Alt            nullable.Nullable[types.PostV1NameDeploymentsAltEnum]   `json:"alt,omitempty"`
	Callback       nullable.Nullable[string]                               `json:"callback,omitempty"`
	Fields         nullable.Nullable[string]                               `json:"fields,omitempty"`
	Key            nullable.Nullable[string]                               `json:"key,omitempty"`
	OauthToken     nullable.Nullable[string]                               `json:"oauthToken,omitempty"`
	Override       nullable.Nullable[bool]                                 `json:"override,omitempty"`
	PrettyPrint    nullable.Nullable[bool]                                 `json:"prettyPrint,omitempty"`
	QuotaUser      nullable.Nullable[string]                               `json:"quotaUser,omitempty"`
	ServiceAccount nullable.Nullable[string]                               `json:"serviceAccount,omitempty"`
	UploadType     nullable.Nullable[string]                               `json:"uploadType,omitempty"`
	UploadProtocol nullable.Nullable[string]                               `json:"uploadProtocol,omitempty"`
}
