// Code generated by Sideko (sideko.dev)
package analytics

import (
	sdkcore "apigee_api/core"
	datastores "apigee_api/resources/v1/analytics/datastores"
	datastores_test "apigee_api/resources/v1/analytics/datastores_test"
	exports "apigee_api/resources/v1/analytics/exports"
	http "net/http"
)

type Client struct {
	coreClient     *sdkcore.CoreClient
	Datastores     *datastores.Client
	Exports        *exports.Client
	DatastoresTest *datastores_test.Client
}
type RequestModifier = func(req *http.Request) error

// Instantiate a new resource client
func NewClient(coreClient *sdkcore.CoreClient) *Client {
	client := Client{
		coreClient:     coreClient,
		Datastores:     datastores.NewClient(coreClient),
		Exports:        exports.NewClient(coreClient),
		DatastoresTest: datastores_test.NewClient(coreClient),
	}

	return &client
}

// register api methods (keep comment for code generation)
